import { sample, topic } from "../phase1Helpers.js";

const C = "foundations";

export const foundationLessons = [
  topic({ id: "numbers-signs", chapterId: C, order: 1, title: "Numbers, Signs & Order of Operations", term: "number", definition: "A quantity used to count, measure, or locate a position on a number line.", analogy: "A point on a road where zero is the town centre", termExample: "-3 means three units below or left of zero.", nonExample: "The minus sign by itself is an operation, not a complete quantity.", plain: "Numbers tell us how much; signs tell us direction or whether an operation adds or removes.", realTitle: "A bank balance", realBody: "A balance of 50 means money available; -20 means twenty is owed. The sign changes the meaning even when the size is similar.", ml: "Model errors, feature values, weights, and gradients may be positive, zero, or negative, so sign interpretation is essential.", wrong: "A negative number is always bad.", correction: "Negative means below zero or opposite direction; whether that is good or bad depends on context.", samples: [
    sample("Read a signed quantity", "A temperature moves from 4°C to -3°C. What is the change?", ["Write final minus initial: -3-4.", "Subtracting 4 moves four more units left."], "-7°C", "Temperature fell by seven degrees."),
    sample("Use operation order", "Evaluate 2 + 3 × 4.", ["Multiplication comes before addition.", "Compute 3×4=12.", "Then 2+12=14."], "14", "Doing addition first would incorrectly give 20."),
    sample("Interpret a model weight", "A feature value is 5 and its weight is -2. Find their contribution.", ["Multiply value by weight.", "5×(-2)=-10."], "-10", "This feature pushes the model score downward by ten units.")
  ]}),
  topic({ id: "fractions-ratios-percentages", chapterId: C, order: 2, title: "Fractions, Ratios, Percentages & Decimals", prerequisites: ["numbers-signs"], requiredTermIds: ["numbers-signs"], term: "fraction", definition: "A number describing some equal parts of a whole, written as numerator divided by denominator.", analogy: "Slices taken from an evenly divided pizza", termExample: "3/4 means three of four equal parts and equals 0.75 or 75%.", nonExample: "Three slices from pizzas cut into different-sized pieces is not automatically 3/4.", plain: "Fractions, decimals, ratios, and percentages are different ways to describe the same relative amount.", realTitle: "A shop discount", realBody: "A 20% discount means removing 20 out of every 100 units of the original price.", ml: "Accuracy, probabilities, train-test splits, learning rates, and normalized features are commonly expressed as fractions or percentages.", wrong: "A larger denominator always creates a larger fraction.", correction: "With the same numerator, a larger positive denominator creates smaller pieces and therefore a smaller fraction.", samples: [
    sample("Convert a fraction", "Convert 3/5 to a decimal and percentage.", ["Divide 3 by 5 to get 0.6.", "Multiply 0.6 by 100 to get 60%."], "0.6 = 60%", "All three forms represent the same proportion."),
    sample("Apply a percentage", "A dataset has 200 rows. Put 20% in the test set.", ["Write 20%=0.20.", "Multiply 200×0.20."], "40 rows", "The remaining 160 rows are not part of the test set."),
    sample("Interpret a rate", "A classifier is correct on 87 of 100 examples. Find accuracy.", ["Accuracy is correct divided by total.", "87/100=0.87.", "Convert to percent."], "87%", "Accuracy is a ratio, not a count by itself.")
  ]}),
  topic({ id: "powers-roots-scientific", chapterId: C, order: 3, title: "Powers, Roots & Scientific Notation", prerequisites: ["fractions-ratios-percentages"], requiredTermIds: ["numbers-signs", "fractions-ratios-percentages"], term: "exponent", definition: "A small raised number telling how many times a base is multiplied by itself.", analogy: "A compact repeat instruction", termExample: "2³ means 2×2×2=8.", nonExample: "2×3=6 is multiplication, not the meaning of 2³.", plain: "Powers compress repeated multiplication; roots undo powers; scientific notation makes extremely large or small values readable.", realTitle: "Area and scale", realBody: "Doubling the side of a square multiplies its area by 2²=4, not merely by two.", ml: "Squared errors, Euclidean distance, variance, tiny probabilities, and dataset sizes all use powers, roots, or scientific notation.", wrong: "The exponent is multiplied by the base.", correction: "An exponent describes repeated multiplication of the base; 3² is 3×3, not 3×2.", samples: [
    sample("Evaluate a power", "Evaluate (-3)².", ["Parentheses make -3 the complete base.", "Multiply (-3)×(-3)."], "9", "Two negative factors produce a positive result."),
    sample("Undo a square", "Find the positive square root of 49.", ["Ask which positive number squared equals 49.", "7×7=49."], "7", "The radical symbol requests the principal non-negative root."),
    sample("Read a small learning rate", "Write 0.0001 in scientific notation.", ["Move the decimal four places right to get 1.", "Moving right gives a negative exponent."], "1×10⁻⁴", "Scientific notation makes the scale immediately visible.")
  ]}),
  topic({ id: "variables-expressions", chapterId: C, order: 4, title: "Variables & Algebraic Expressions", prerequisites: ["powers-roots-scientific"], requiredTermIds: ["numbers-signs"], term: "variable", definition: "A symbol standing for a value that may be unknown or allowed to change.", analogy: "A labelled container whose contents can vary", termExample: "In 3x+2, x is a variable and 3 is its coefficient.", nonExample: "The fixed number 7 in one calculation is a constant, not the changing input.", plain: "Algebra uses names for quantities so one rule can work for many numerical cases.", realTitle: "A taxi bill", realBody: "If x is kilometres travelled, 3x+5 represents a charge of 3 per kilometre plus a fixed starting fee of 5.", ml: "Features, weights, predictions, and losses are represented by variables so models can work across many observations.", wrong: "Letters in algebra are abbreviations that can be ignored.", correction: "Every variable represents a defined quantity; write its meaning and units before manipulating it.", samples: [
    sample("Substitute a value", "Evaluate 3x+2 when x=4.", ["Replace x with 4.", "Multiply 3×4=12.", "Add 2."], "14", "Substitution turns a general expression into one numerical case."),
    sample("Collect like terms", "Simplify 2x+3x-4.", ["2x and 3x describe the same variable unit.", "Add their coefficients: 2+3=5.", "Keep the constant -4."], "5x-4", "Only like terms can be combined."),
    sample("Read a model score", "For z=wx+b, use w=2, x=-3, b=1.", ["Multiply 2×(-3)=-6.", "Add bias 1."], "z=-5", "The negative input and positive weight create a negative contribution.")
  ]}),
  topic({ id: "equations-inequalities", chapterId: C, order: 5, title: "Equations & Inequalities", prerequisites: ["variables-expressions"], requiredTermIds: ["variables-expressions"], term: "equation", definition: "A statement that two expressions have the same value.", analogy: "A balanced scale with equal weight on both sides", termExample: "3x+5=17 states that both sides are equal for x=4.", nonExample: "3x+5 without an equals sign is an expression, not an equation.", plain: "Solving an equation means finding values that make equality true; an inequality describes a range rather than one exact match.", realTitle: "Meeting a budget", realBody: "If a fixed fee plus hourly cost must stay below a budget, the condition is an inequality rather than an exact equation.", ml: "Decision thresholds, optimization constraints, and margin conditions use equations and inequalities.", wrong: "Moving a term across the equals sign magically changes its sign.", correction: "The sign changes because the same inverse operation is applied to both sides of the equation.", samples: [
    sample("Solve one equation", "Solve 3x+5=17.", ["Subtract 5 from both sides: 3x=12.", "Divide both sides by 3."], "x=4", "Substitution confirms 3(4)+5=17."),
    sample("Solve an inequality", "Solve 2x+1<9.", ["Subtract 1: 2x<8.", "Divide by positive 2, so the inequality direction stays."], "x<4", "Every number below four satisfies the condition."),
    sample("Use a classification threshold", "Predict class 1 when p≥0.5. What class is p=0.42?", ["Compare 0.42 with 0.5.", "0.42 is below the threshold."], "Class 0", "The inequality converts a probability into a decision.")
  ]}),
  topic({ id: "functions-domain-range", chapterId: C, order: 6, title: "Functions, Inputs, Outputs, Domain & Range", prerequisites: ["equations-inequalities"], requiredTermIds: ["variables-expressions", "equations-inequalities"], term: "function", definition: "A rule assigning exactly one output to each allowed input.", analogy: "A machine that follows one consistent recipe", termExample: "f(x)=2x+1 sends input 3 to output 7.", nonExample: "A rule that gives both 4 and 9 for the same input without another condition is not a function.", plain: "A function is an input-output rule; domain means allowed inputs and range means outputs the rule can produce.", realTitle: "Currency conversion", realBody: "A conversion rule takes one money amount as input and returns one converted amount as output.", ml: "Every model is a function mapping input features to predictions, scores, embeddings, or probabilities.", wrong: "f(x) means f multiplied by x.", correction: "f(x) names the output of function f when the input is x.", formulas: ["linear-function"], samples: [
    sample("Evaluate a function", "For f(x)=2x+1, find f(3).", ["Replace x with 3.", "Compute 2×3+1."], "7", "The function maps one input to one output."),
    sample("Check a domain", "For g(x)=1/x, is x=0 allowed?", ["Substitute zero mentally.", "Division by zero is undefined."], "No; x=0 is excluded", "Domain restrictions prevent invalid operations."),
    sample("Read an ML function", "A model maps 4 input features to one probability. What are its input and output shapes?", ["Count the supplied features.", "Count the returned prediction."], "Input has 4 values; output has 1 value", "Function language describes model interfaces as well as formulas.")
  ]}),
  topic({ id: "graphs-slope-intercept", chapterId: C, order: 7, title: "Coordinates, Graphs, Slope & Intercept", prerequisites: ["functions-domain-range"], requiredTermIds: ["functions-domain-range"], term: "slope", definition: "The change in vertical output divided by the corresponding change in horizontal input.", analogy: "Steepness of a road measured as rise per unit forward", termExample: "A slope of 3 means output rises by 3 when input rises by 1.", nonExample: "The y-intercept is a starting value, not the rate of change.", plain: "A graph pictures a function; slope describes direction and rate, while the intercept gives the output at input zero.", realTitle: "Hourly earnings", realBody: "A pay graph starts at any fixed bonus and rises by the hourly wage for every hour worked.", ml: "Regression coefficients are slopes and the bias is an intercept; learning curves graph model behaviour over time.", wrong: "Slope is just the height of a line.", correction: "Slope is a ratio of changes, so it depends on both vertical and horizontal movement.", formulas: ["linear-function"], samples: [
    sample("Find a slope", "Find the slope through (1,2) and (3,8).", ["Output change is 8-2=6.", "Input change is 3-1=2.", "Divide 6/2."], "3", "Output rises three units per input unit."),
    sample("Read an intercept", "For y=4x-2, find the y-intercept.", ["Set x=0.", "Compute y=4(0)-2."], "-2", "The graph crosses the vertical axis below zero."),
    sample("Interpret a regression coefficient", "A price model has slope -5 for distance. What does it mean?", ["Read the sign: negative means decrease.", "Read the size: five output units per distance unit."], "Each extra distance unit lowers predicted price by 5", "A coefficient is meaningful only with feature and target units.")
  ]}),
  topic({ id: "exponents-logarithms", chapterId: C, order: 8, title: "Exponents & Logarithms", prerequisites: ["powers-roots-scientific", "functions-domain-range"], requiredTermIds: ["powers-roots-scientific", "functions-domain-range"], term: "logarithm", definition: "The exponent needed on a chosen base to produce a positive number.", analogy: "Asking how many repeated multiplication steps reached the result", termExample: "log₂(8)=3 because 2³=8.", nonExample: "log(0) is not a finite real number.", plain: "Exponentials build values through repeated multiplication; logarithms reverse that process.", realTitle: "Compounding growth", realBody: "Growth multiplies repeatedly; a logarithm can answer how many growth periods were needed.", ml: "Log-likelihood and cross-entropy turn probability products into sums and strongly penalize tiny probabilities for the true answer.", wrong: "log(a+b)=log(a)+log(b).", correction: "Logs split products, not sums: log(ab)=log(a)+log(b).", formulas: ["logarithm"], samples: [
    sample("Evaluate a logarithm", "Find log₂(32).", ["Ask 2 to what power equals 32.", "2×2×2×2×2=32."], "5", "The logarithm returns an exponent."),
    sample("Undo a logarithm", "If ln(x)=2, solve for x.", ["Natural log has base e.", "Exponentiate both sides with base e."], "x=e²", "Exponentiation and logarithms are inverse functions."),
    sample("Compare prediction penalties", "Which has larger -log(p): p=0.9 or p=0.01?", ["Log of a tiny positive number is very negative.", "Negating it makes a large positive loss."], "p=0.01", "A confidently wrong prediction receives a large cross-entropy penalty.")
  ]}),
  topic({ id: "summation-subscripts-sets", chapterId: C, order: 9, title: "Summation, Subscripts, Sets & Notation", prerequisites: ["variables-expressions", "functions-domain-range"], requiredTermIds: ["variables-expressions"], term: "summation", definition: "A compact instruction to add a sequence of indexed terms.", analogy: "A loop that visits numbered items and adds each one", termExample: "Σ from i=1 to 3 of xᵢ means x₁+x₂+x₃.", nonExample: "The sigma symbol does not mean multiply all terms.", plain: "Indices label positions, sets collect objects, and sigma notation compresses repeated addition.", realTitle: "Adding a bill", realBody: "A receipt total adds the price at each numbered line item; summation notation expresses the same repeated action.", ml: "Loss functions sum errors over examples, probability sums outcomes, and matrix formulas sum matching coordinates.", wrong: "A subscript is an exponent.", correction: "A subscript labels an item or coordinate; an exponent indicates a power unless context defines another convention.", formulas: ["summation"], samples: [
    sample("Expand a sum", "Expand Σᵢ₌₁³ xᵢ.", ["Start with i=1.", "Write one term for i=1,2,3.", "Join them with addition."], "x₁+x₂+x₃", "The limits control which indexed terms appear."),
    sample("Evaluate a sum", "Evaluate Σᵢ₌₁⁴ i.", ["Generate 1+2+3+4.", "Add in order."], "10", "The index itself can be the quantity being summed."),
    sample("Read average loss", "Explain (1/n)Σᵢ Lᵢ.", ["Σ adds one loss per example.", "n is the number of examples.", "Dividing by n forms the average."], "Mean loss across n examples", "Subscripts connect each loss to its data example.")
  ]})
];

