import { sample, topic } from "../phase1Helpers.js";

const C = "linear-algebra";
const make = (order, config) => topic({ chapterId: C, order, ...config });

export const linearAlgebraLessons = [
  make(1, { id: "scalars-vectors-tensors", title: "Scalars, Vectors & Tensors", prerequisites: ["summation-subscripts-sets"], requiredTermIds: ["numbers-signs"], term: "scalar", definition: "One numerical value with magnitude and possibly a sign.", analogy: "One reading on a measuring instrument", termExample: "Temperature 24°C is one scalar.", nonExample: "[24, 60, 5] contains several values and is not one scalar.", extraVocabulary: [
    ["vector", "vector", "An ordered list of numbers representing components of one object.", "An arrow or a row of labelled measurements", "[age, income, spending] is a three-component vector.", "An unordered bag of unrelated labels is not a numerical vector.", "Feature rows, embeddings, weights, and gradients are vectors."],
    ["tensor", "tensor", "A multidimensional rectangular collection of numbers; scalars, vectors, and matrices are lower-dimensional cases.", "A stack of tables, possibly stacked again", "A batch of 32 RGB images can have shape 32×3×224×224.", "A Python list with inconsistent row lengths is not a rectangular tensor.", "Deep-learning data, parameters, and activations are tensors."]
  ], plain: "A scalar is one number, a vector is one ordered line of numbers, and a tensor generalizes the idea to more axes.", realTitle: "One patient record", realBody: "One blood-pressure value is a scalar; several measurements form a vector; measurements for many patients over time form a tensor.", ml: "ML turns observations and parameters into vectors and tensors so many related numbers can be processed together.", wrong: "A vector is simply several numbers written near each other.", correction: "Vector order and component meaning matter; changing their order changes what the vector represents.", formulas: ["vector-notation"], samples: [
    sample("Classify an object", "Classify 7, [7,2], and a 10×3 table.", ["Count axes and values.", "One value is scalar; one ordered axis is vector; rows and columns form a matrix tensor."], "scalar, vector, matrix", "Shape tells how numbers are organized."),
    sample("Read a feature vector", "A customer is represented by [25, 4000, 8]. What might each component mean?", ["Read the defined component order.", "Attach one meaning and unit to each position."], "For example: age 25, income 4000, visits 8", "Without labels, numbers alone are ambiguous."),
    sample("Read tensor shape", "A batch has shape 32×3×64×64. Interpret it.", ["Read axes left to right.", "Use the image convention batch, channels, height, width."], "32 images, 3 channels, each 64×64", "Tensor axes encode data organization, not multiplication.")
  ]}),
  make(2, { id: "vector-arithmetic", title: "Vector Components & Arithmetic", prerequisites: ["scalars-vectors-tensors"], requiredTermIds: ["vector"], term: "vector arithmetic", definition: "Adding, subtracting, or scaling vectors component by component while preserving component order.", analogy: "Combining two itemized shopping lists line by line", termExample: "(2,3)+(4,1)=(6,4).", nonExample: "Adding a two-component vector to a three-component vector is not defined componentwise.", plain: "Vector arithmetic combines matching components; scalar multiplication stretches or reverses every component together.", realTitle: "Combining movements", realBody: "Walking 3 east and 2 north, then 1 east and 4 north, produces total movement 4 east and 6 north.", ml: "Model updates subtract a scaled gradient vector from a parameter vector.", wrong: "Vector addition joins the lists end to end.", correction: "Addition combines matching positions and requires compatible dimensions.", formulas: ["vector-addition"], samples: [
    sample("Add vectors", "Add (2,-1)+(3,4).", ["Add first components: 2+3.", "Add second components: -1+4."], "(5,3)", "Each coordinate keeps its meaning."),
    sample("Scale a vector", "Compute -2(3,-1).", ["Multiply every component by -2.", "Preserve component positions."], "(-6,2)", "Negative scaling reverses direction and doubles length."),
    sample("Apply an update", "Weights are (5,2), gradient is (1,-3), learning rate is 0.1. Compute w-0.1g.", ["Scale gradient: (0.1,-0.3).", "Subtract componentwise."], "(4.9,2.3)", "A negative gradient component makes that weight increase after subtraction.")
  ]}),
  make(3, { id: "vector-magnitude-distance", title: "Vector Magnitude & Distance", prerequisites: ["vector-arithmetic", "powers-roots-scientific"], requiredTermIds: ["vector", "powers-roots-scientific"], term: "magnitude", definition: "The non-negative Euclidean length of a vector.", analogy: "The length of an arrow regardless of where it points", termExample: "The vector (3,4) has magnitude 5.", nonExample: "3+4=7 is not the Euclidean length of (3,4).", plain: "Magnitude measures vector size; distance is the magnitude of the difference between two vectors.", realTitle: "Straight-line travel", realBody: "Moving 3 blocks east and 4 north places you 5 straight-line blocks from the start.", ml: "k-NN, clustering, similarity systems, regularization, and gradient clipping use vector lengths or distances.", wrong: "Magnitude can be negative when vector components are negative.", correction: "Squared components and the square root make Euclidean magnitude non-negative.", formulas: ["vector-magnitude", "distance"], samples: [
    sample("Find magnitude", "Find ||(3,4)||₂.", ["Square components: 9 and 16.", "Add to 25.", "Take √25."], "5", "The result is a length, not a direction."),
    sample("Find distance", "Find distance between (1,2) and (4,6).", ["Subtract to get (3,4).", "Find its magnitude."], "5", "Distance is unchanged if the subtraction order is reversed."),
    sample("Compare neighbours", "Which is closer to (0,0): (1,1) or (3,0)?", ["Lengths are √2 and 3.", "Compare positive lengths."], "(1,1)", "Distance-based models select the smaller distance.")
  ]}),
  make(4, { id: "unit-vectors-normalization", title: "Unit Vectors & Normalization", prerequisites: ["vector-magnitude-distance"], requiredTermIds: ["vector", "vector-magnitude-distance"], term: "unit vector", definition: "A vector with magnitude exactly one.", analogy: "A direction arrow standardized to one unit long", termExample: "(3/5,4/5) is the unit version of (3,4).", nonExample: "The zero vector cannot be normalized because its length is zero.", plain: "Normalization divides by magnitude to keep direction while removing original size.", realTitle: "Comparing directions fairly", realBody: "Two people may walk the same direction for different distances; unit vectors compare direction without distance.", ml: "Embedding normalization makes cosine or dot-product comparison focus on direction rather than raw scale.", wrong: "Normalization makes every component add to one.", correction: "Euclidean normalization makes squared components sum to one; it is different from probability normalization.", formulas: ["unit-vector", "vector-magnitude"], samples: [
    sample("Normalize a vector", "Normalize (3,4).", ["Magnitude is 5.", "Divide each component by 5."], "(0.6,0.8)", "Its direction is unchanged and length is one."),
    sample("Verify unit length", "Verify (1/√2,1/√2) is unit length.", ["Square both components to get 1/2 each.", "Add to 1 and take square root."], "Magnitude 1", "Equal components point at 45 degrees."),
    sample("Normalize an embedding", "An embedding is (0,10). Find its normalized form.", ["Magnitude is 10.", "Divide both coordinates by 10."], "(0,1)", "Large original size no longer dominates comparison.")
  ]}),
  make(5, { id: "dot-product-angle", title: "Dot Product, Angle & Cosine", prerequisites: ["unit-vectors-normalization"], requiredTermIds: ["vector", "unit-vectors-normalization"], term: "dot product", definition: "A scalar found by multiplying matching vector components and adding the products.", analogy: "Measuring how much one arrow helps along another arrow", termExample: "(1,2)·(3,4)=1×3+2×4=11.", nonExample: "Returning (3,8) is componentwise multiplication, not the dot product.", plain: "The dot product combines magnitude and alignment: positive aligns, zero is perpendicular, and negative opposes.", realTitle: "Pushing a trolley", realBody: "Only the part of your force pointing along the trolley's movement helps it move forward.", ml: "Linear models, neural layers, cosine similarity, recommendations, search, and attention rely on dot products.", wrong: "A large dot product always means strong directional similarity.", correction: "Raw dot product also grows with magnitude; normalize first when direction alone should matter.", formulas: ["dot-product"], samples: [
    sample("Calculate a dot product", "Find (2,3)·(4,5).", ["Multiply matching components: 8 and 15.", "Add the products."], "23", "One scalar summarizes the interaction."),
    sample("Read zero", "Find (1,0)·(0,7) and interpret.", ["Compute 1×0+0×7.", "Compare result with zero."], "0; perpendicular", "Neither vector has a component along the other."),
    sample("Compare interest", "A user vector (1,2) meets products A=(2,1), B=(-2,-1). Which aligns?", ["Dot with A is 4.", "Dot with B is -4.", "Compare signs."], "Product A", "Positive alignment supports recommendation; negative opposes preference.")
  ]}),
  make(6, { id: "matrix-anatomy-types", title: "Matrix Anatomy, Dimensions & Types", prerequisites: ["scalars-vectors-tensors"], requiredTermIds: ["vector"], term: "matrix", definition: "A rectangular arrangement of numbers organized into rows and columns.", analogy: "A spreadsheet where position has mathematical meaning", termExample: "A 2×3 matrix has two rows and three columns.", nonExample: "Rows with different numbers of entries do not form a rectangular matrix.", plain: "Matrix shape is rows by columns; special matrix types have structures that simplify operations.", realTitle: "A grade table", realBody: "Rows can represent students and columns subjects, so each entry has a row and column meaning.", ml: "Datasets, batches, weights, transformations, and covariance structures are stored as matrices.", wrong: "A 2×3 matrix has two columns and three rows.", correction: "Matrix dimensions are always stated rows first, then columns.", formulas: ["matrix-shape"], samples: [
    sample("Read a shape", "What is the shape of [[1,2,3],[4,5,6]]?", ["Count rows: 2.", "Count entries per row: 3."], "2×3", "Shape predicts which multiplications are possible."),
    sample("Identify a type", "Classify [[1,0],[0,1]].", ["Check diagonal entries.", "Check off-diagonal zeros."], "2×2 identity matrix", "It leaves vectors unchanged when multiplied."),
    sample("Read dataset orientation", "X has shape 100×8 with rows as examples. Interpret it.", ["First dimension counts examples.", "Second counts features."], "100 examples and 8 features", "Always state the chosen data convention.")
  ]}),
  make(7, { id: "matrix-vector-multiplication", title: "Matrix × Vector Multiplication", prerequisites: ["matrix-anatomy-types", "dot-product-angle"], requiredTermIds: ["matrix-anatomy-types", "dot-product-angle"], term: "matrix-vector product", definition: "A new vector formed by taking the dot product of each matrix row with the input vector.", analogy: "Several weighted recipes applied to the same ingredients", termExample: "A 2×3 matrix times a 3-vector produces a 2-vector.", nonExample: "Multiplying only matching visible entries ignores the row-dot-vector rule.", plain: "Each matrix row asks one weighted question about the input vector.", realTitle: "Two scoring rules", realBody: "The same customer information can be sent through separate weighted scorecards for risk and loyalty.", ml: "A dense layer computes many neuron scores by multiplying a weight matrix by an input vector.", wrong: "Any matrix can multiply any vector.", correction: "The vector length must equal the matrix column count.", formulas: ["matrix-product", "linear-transform"], samples: [
    sample("Multiply matrix by vector", "Compute [[1,2],[0,1]](3,-1).", ["First row dot vector: 3-2=1.", "Second row dot vector: -1."], "(1,-1)", "Each output component comes from one row."),
    sample("Check dimensions", "Can a 2×3 matrix multiply a length-2 vector?", ["Matrix columns are 3.", "Vector length is 2.", "Inner dimensions do not match."], "No", "Dimension checking prevents meaningless arithmetic."),
    sample("Compute neuron scores", "W=[[1,-1],[2,0]], x=(4,3). Find Wx.", ["Row one gives 4-3.", "Row two gives 8+0."], "(1,8)", "Two rows produce two neuron pre-activations.")
  ]}),
  make(8, { id: "matrix-matrix-multiplication", title: "Matrix × Matrix Multiplication", prerequisites: ["matrix-vector-multiplication"], requiredTermIds: ["matrix-vector-multiplication"], term: "matrix multiplication", definition: "An operation where each output entry is a row of the first matrix dotted with a column of the second.", analogy: "Applying one table of transformations after another", termExample: "A 2×3 matrix times a 3×4 matrix produces a 2×4 matrix.", nonExample: "Multiplying entries in identical positions is the Hadamard product, not matrix multiplication.", plain: "Matrix multiplication composes many row-column dot products, and order usually matters.", realTitle: "Two-stage conversion", realBody: "One table converts ingredients to nutrients and another converts nutrients to scores; their product combines both stages.", ml: "Batched predictions and stacked neural layers are expressed through matrix products.", wrong: "AB always equals BA.", correction: "Matrix multiplication is generally not commutative, and BA may have a different meaning or be undefined.", formulas: ["matrix-product"], samples: [
    sample("Multiply 2×2 matrices", "Compute [[1,2],[0,1]][[2,0],[3,1]].", ["Compute row1·col1=8 and row1·col2=2.", "Compute row2·col1=3 and row2·col2=1."], "[[8,2],[3,1]]", "Every entry has one row-column calculation."),
    sample("Predict output shape", "A is 5×3 and B is 3×2. Find AB shape.", ["Inner dimensions 3 match.", "Keep outer dimensions 5 and 2."], "5×2", "Shape can be known before values are calculated."),
    sample("Compose layers", "X is 32×10 and W is 10×4. Find XW shape.", ["Ten feature dimensions match.", "Keep batch 32 and output width 4."], "32×4", "Every batch row receives four outputs.")
  ]}),
  make(9, { id: "transpose-symmetry", title: "Transpose & Symmetric Matrices", prerequisites: ["matrix-anatomy-types"], requiredTermIds: ["matrix-anatomy-types"], term: "transpose", definition: "The matrix formed by turning rows into columns.", analogy: "Reflecting a table across its main diagonal", termExample: "[[1,2],[3,4]]ᵀ=[[1,3],[2,4]].", nonExample: "Changing signs or reversing values is not transposition.", plain: "Transpose swaps matrix orientation; a symmetric matrix remains unchanged after this swap.", realTitle: "Switching a table's viewpoint", realBody: "A people-by-products table becomes products-by-people when transposed.", ml: "Dot products, covariance matrices, least squares, gradients, and attention use transposes to align dimensions.", wrong: "Transpose means calculate an inverse.", correction: "Transpose only swaps indices; it does not undo the matrix transformation.", formulas: ["transpose"], samples: [
    sample("Transpose a matrix", "Transpose [[1,2,3],[4,5,6]].", ["Turn first row into first column.", "Turn second row into second column."], "[[1,4],[2,5],[3,6]]", "Shape changes from 2×3 to 3×2."),
    sample("Check symmetry", "Is [[2,1],[1,3]] symmetric?", ["Transpose it.", "Compare every mirrored entry."], "Yes", "Off-diagonal entries match across the diagonal."),
    sample("Align a batch", "X is 100×5. What is XᵀX shape?", ["Xᵀ is 5×100.", "Multiply 5×100 by 100×5."], "5×5", "The result compares features with features.")
  ]}),
  make(10, { id: "determinant-collapse", title: "Determinants & Geometric Collapse", prerequisites: ["matrix-matrix-multiplication"], requiredTermIds: ["matrix-anatomy-types"], term: "determinant", definition: "A signed number measuring how a square matrix scales area or volume and whether it collapses dimensions.", analogy: "An area-stretch meter for a transformation", termExample: "diag(2,3) has determinant 6 and multiplies area by six.", nonExample: "A determinant is not defined for a non-square matrix in elementary linear algebra.", plain: "A nonzero determinant preserves dimensional information; zero means some direction collapses and the matrix cannot be inverted.", realTitle: "Flattening a sheet", realBody: "Stretching a sheet keeps area, but pressing it onto a line collapses area to zero.", ml: "Invertibility, Gaussian densities, covariance matrices, and change-of-variable calculations depend on determinants.", wrong: "Determinant is the sum of all matrix entries.", correction: "For a 2×2 matrix it is ad-bc, which captures interaction between rows and columns.", formulas: ["determinant"], samples: [
    sample("Calculate a determinant", "Find det([[2,1],[3,4]]).", ["Use ad-bc.", "Compute 2×4-1×3."], "5", "Nonzero means no complete dimensional collapse."),
    sample("Detect collapse", "Find det([[1,2],[2,4]]).", ["Compute 1×4-2×2.", "The result is zero."], "0", "The second row repeats the first direction, so information is lost."),
    sample("Read scaling", "A 2D transformation has determinant -3. Interpret it.", ["Absolute value 3 gives area scale.", "Negative sign indicates orientation reversal."], "Area triples and orientation flips", "Sign and magnitude carry different geometric information.")
  ]}),
  make(11, { id: "inverse-systems", title: "Matrix Inverses & Systems of Equations", prerequisites: ["determinant-collapse"], requiredTermIds: ["determinant-collapse"], term: "matrix inverse", definition: "A matrix that reverses the effect of an invertible square matrix.", analogy: "An undo operation for a transformation", termExample: "A⁻¹A=I returns every vector unchanged.", nonExample: "A matrix with determinant zero has no inverse.", plain: "An inverse undoes a matrix transformation and can solve a linear system when the transformation has not lost information.", realTitle: "Undoing a conversion", realBody: "If one rule converts original quantities into mixtures, its inverse can recover the originals only when no information was merged irreversibly.", ml: "Least-squares theory and Gaussian models use inverses, though numerical ML usually solves systems without explicitly forming one.", wrong: "Invert every entry separately to invert a matrix.", correction: "Matrix inverse is defined by AA⁻¹=I; entrywise reciprocals generally fail this test.", formulas: ["matrix-inverse", "determinant"], samples: [
    sample("Verify an inverse", "For A=diag(2,4), propose A⁻¹.", ["Undo scaling by 2 with 1/2.", "Undo scaling by 4 with 1/4."], "diag(1/2,1/4)", "Their product is the identity."),
    sample("Check invertibility", "Can [[1,2],[2,4]] be inverted?", ["Calculate determinant 4-4.", "A zero determinant fails invertibility."], "No", "One equation repeats the other and cannot recover two unknowns."),
    sample("Solve a diagonal system", "Solve diag(2,5)x=(8,15).", ["Divide first equation by 2.", "Divide second equation by 5."], "x=(4,3)", "The inverse scaling recovers each coordinate.")
  ]}),
  make(12, { id: "rank-column-null", title: "Rank, Column Space & Null Space", prerequisites: ["inverse-systems"], requiredTermIds: ["matrix-anatomy-types"], term: "rank", definition: "The number of independent output directions a matrix can produce.", analogy: "Counting genuinely different tools rather than duplicated copies", termExample: "A matrix with two proportional columns has only one independent column direction.", nonExample: "Rank is not simply the number of nonzero entries.", plain: "Column space describes reachable outputs, null space describes inputs erased to zero, and rank counts independent output information.", realTitle: "Duplicate measurements", realBody: "Recording the same measurement twice creates more columns but not more independent information.", ml: "Rank reveals redundant features, identifiability problems, compression opportunities, and information loss.", wrong: "A matrix with many nonzero entries must have full rank.", correction: "Nonzero rows or columns can still be dependent combinations of others.", formulas: ["rank-nullity"], samples: [
    sample("Spot reduced rank", "Find rank of [[1,2],[2,4]].", ["Observe row two is twice row one.", "Only one independent direction remains."], "Rank 1", "The 2×2 matrix is not full rank."),
    sample("Find a null vector", "Find nonzero v with [[1,2],[2,4]]v=0.", ["Solve x+2y=0.", "Choose y=1, giving x=-2."], "v=(-2,1)", "This input direction is collapsed to zero."),
    sample("Interpret feature redundancy", "Feature B is exactly 3× feature A. What happens to rank?", ["B adds no new direction.", "The two columns are dependent."], "Rank does not increase", "Duplicated information can destabilize parameter estimates.")
  ]}),
  make(13, { id: "linear-transformations", title: "Linear Transformations", prerequisites: ["matrix-vector-multiplication", "rank-column-null"], requiredTermIds: ["matrix-vector-multiplication"], term: "linear transformation", definition: "A mapping that preserves vector addition and scalar multiplication and can be represented by a matrix.", analogy: "A consistent grid-stretch, rotation, reflection, or shear", termExample: "T(x)=2x doubles every vector and preserves linear combinations.", nonExample: "T(x)=x+(1,1) is a translation and does not send zero to zero.", plain: "A matrix is not just a table; it is a rule that moves every vector consistently.", realTitle: "Transforming a map", realBody: "A map can be stretched, rotated, or sheared while straight grid lines remain straight and the origin stays fixed.", ml: "Dense layers, feature projections, PCA, embeddings, and convolutions use linear transformations.", wrong: "Every function that moves points is linear.", correction: "A linear map must preserve sums and scaling and must map the zero vector to zero.", formulas: ["linear-transform", "matrix-product"], samples: [
    sample("Apply a scaling", "Apply diag(2,3) to (4,1).", ["Scale x-coordinate by 2.", "Scale y-coordinate by 3."], "(8,3)", "Different axes can stretch differently."),
    sample("Test linearity", "Is T(x)=x+(1,1) linear?", ["Evaluate T(0).", "T(0)=(1,1), not zero."], "No", "Failing one linearity condition is enough."),
    sample("Read a projection", "A transformation maps every (x,y) to (x,0). What does it do?", ["Keep the first coordinate.", "Erase the second coordinate."], "Projects onto the x-axis", "Its null space contains the y-axis.")
  ]}),
  make(14, { id: "basis-coordinates", title: "Standard Basis & Coordinates", prerequisites: ["linear-transformations"], requiredTermIds: ["vector", "linear-transformations"], term: "basis", definition: "A set of independent vectors that can build every vector in a space uniquely.", analogy: "A set of independent measuring directions", termExample: "(1,0) and (0,1) form the standard basis of 2D space.", nonExample: "(1,0) and (2,0) do not span 2D because both point along one line.", plain: "Coordinates tell how much of each basis direction is needed to build a vector.", realTitle: "Describing location", realBody: "A location can be described using east-north directions or another pair of independent directions; the location stays the same while coordinates change.", ml: "Feature representations and embedding coordinates depend on a chosen basis.", wrong: "A vector and its coordinate list are always the same object.", correction: "Coordinates describe a vector relative to a basis; changing basis changes the list, not the underlying vector.", formulas: ["basis-coordinates"], samples: [
    sample("Use standard coordinates", "Write (4,-2) in the standard basis.", ["Coefficient of (1,0) is 4.", "Coefficient of (0,1) is -2."], "[4,-2]", "Standard coordinates match the familiar component list."),
    sample("Check a candidate basis", "Do (1,1) and (1,-1) form a 2D basis?", ["They are not scalar multiples.", "Two independent vectors span 2D."], "Yes", "Independence prevents ambiguous coordinates."),
    sample("Build from coordinates", "Using b₁=(1,1), b₂=(1,-1), build coordinates [1,1].", ["Compute 1b₁+1b₂.", "Add componentwise."], "(2,0)", "Coordinates [1,1] need not mean standard vector (1,1).")
  ]}),
  make(15, { id: "change-of-basis", title: "Change of Basis", prerequisites: ["basis-coordinates", "inverse-systems"], requiredTermIds: ["basis-coordinates", "inverse-systems"], term: "change of basis", definition: "Re-expressing the same vector or transformation using a different basis.", analogy: "Describing the same journey using a rotated compass", termExample: "Vector (2,0) has coordinates (1,1) in basis {(1,1),(1,-1)}.", nonExample: "Physically rotating the vector is a transformation, not merely changing its description.", plain: "Change of basis changes coordinates while keeping the underlying geometric vector unchanged.", realTitle: "Different coordinate systems", realBody: "A pilot and a map may describe the same direction using different reference axes.", ml: "PCA chooses a basis aligned with data variation so fewer coordinates can summarize the data.", wrong: "New coordinates mean the data point moved.", correction: "Only the representation changes during a pure basis change.", formulas: ["change-basis", "basis-coordinates"], samples: [
    sample("Find new coordinates", "Find coordinates of (2,0) in b₁=(1,1), b₂=(1,-1).", ["Solve c₁+c₂=2 and c₁-c₂=0.", "Obtain c₁=c₂=1."], "(1,1)", "The coordinate list changes but reconstructs the same vector."),
    sample("Return to standard basis", "Convert basis coordinates (3,1) using b₁=(1,1), b₂=(1,-1).", ["Compute 3b₁+b₂.", "Add (3,3)+(1,-1)."], "(4,2)", "Basis vectors translate coordinates back to the original space."),
    sample("Interpret PCA coordinates", "What does a PCA coordinate represent?", ["Identify a principal basis direction.", "Measure projection along that direction."], "Amount of the data vector along a principal component", "PCA coordinates are expressed in a learned basis.")
  ]}),
  make(16, { id: "composition-matrix-powers", title: "Composition & Matrix Powers", prerequisites: ["matrix-matrix-multiplication", "linear-transformations"], requiredTermIds: ["matrix-matrix-multiplication", "linear-transformations"], term: "composition", definition: "Applying one transformation and then another, represented by multiplying their matrices in reverse reading order.", analogy: "Following two processing stations in sequence", termExample: "BAx means apply A to x first, then B.", nonExample: "A+B combines outputs but does not represent sequential application.", plain: "Matrix products compose transformations; powers repeat the same transformation.", realTitle: "Repeated growth", realBody: "A population rule applied year after year is a repeated transformation represented by matrix powers.", ml: "Layer stacks, recurrent updates, Markov processes, and iterative algorithms compose transformations.", wrong: "ABx applies A before B because A is written first.", correction: "Operations act from right to left: B is applied first in ABx.", formulas: ["matrix-powers", "matrix-product"], samples: [
    sample("Square a scaling matrix", "For A=diag(2,2), find A².", ["Multiply diagonal factors 2×2.", "Off-diagonal entries remain zero."], "diag(4,4)", "Applying doubling twice multiplies length by four."),
    sample("Repeat three times", "For A=2I, what is A³?", ["Each application scales by 2.", "Multiply scale factors 2³."], "8I", "Powers summarize repeated identical steps."),
    sample("Read layer order", "If h=A x and y=B h, write y directly from x.", ["Substitute h into y.", "Keep order B(Ax)."], "y=BAx", "The later transformation appears on the left.")
  ]}),
  make(17, { id: "eigenvalues-eigenvectors", title: "Eigenvalues & Eigenvectors", prerequisites: ["determinant-collapse", "linear-transformations"], requiredTermIds: ["determinant-collapse", "linear-transformations"], term: "eigenvector", definition: "A nonzero vector whose line is unchanged by a linear transformation; it is only scaled or reversed.", analogy: "A special direction that a stretch does not turn away from itself", termExample: "For diag(3,2), (1,0) is an eigenvector with eigenvalue 3.", nonExample: "The zero vector is excluded because every scale would fit it and reveal no direction.", plain: "Eigenvectors identify preserved directions; eigenvalues tell their scale, sign, and possible collapse.", realTitle: "Stretching patterned fabric", realBody: "Some printed directions stay pointing the same way as fabric stretches, even though their lengths change.", ml: "PCA, spectral clustering, stability analysis, covariance structure, and repeated transformations use eigenpairs.", wrong: "Every vector is an eigenvector of every matrix.", correction: "Only special nonzero directions that remain on their own line qualify.", formulas: ["eigen-equation", "characteristic-equation"], samples: [
    sample("Verify an eigenpair", "For A=diag(3,2), verify v=(1,0), λ=3.", ["Compute Av=(3,0).", "Compute 3v=(3,0).", "Compare."], "The pair is valid", "Both sides match and v is nonzero."),
    sample("Find diagonal eigenvalues", "Find eigenvalues of diag(5,-2).", ["Coordinate axes remain unchanged in direction.", "Read scale on each axis."], "5 and -2", "Negative eigenvalue reverses one eigen-direction."),
    sample("Interpret λ=0", "What does eigenvalue zero mean?", ["Use Av=0v.", "The eigenvector maps to zero."], "That direction collapses", "The transformation loses information along that direction.")
  ]}),
  make(18, { id: "eigendecomposition", title: "Eigendecomposition", prerequisites: ["eigenvalues-eigenvectors", "change-of-basis"], requiredTermIds: ["eigenvalues-eigenvectors", "change-of-basis"], term: "eigendecomposition", definition: "Factoring a diagonalizable matrix into eigenvector coordinates, diagonal eigenvalue scaling, and a return to original coordinates.", analogy: "Rotate to easy directions, stretch independently, then rotate back", termExample: "A=CΛC⁻¹ stores eigenvectors in C and eigenvalues on Λ's diagonal.", nonExample: "Not every matrix has enough independent eigenvectors to form this decomposition.", plain: "Eigendecomposition reveals a complicated transformation as independent scaling along special directions.", realTitle: "Using natural axes", realBody: "A diagonal stretch is easy; eigendecomposition finds coordinates where a more complicated transformation behaves that way.", ml: "It simplifies matrix powers and motivates PCA, spectral methods, and dynamical-system analysis.", wrong: "C contains eigenvalues and Λ contains eigenvectors.", correction: "Columns of C are eigenvectors; diagonal entries of Λ are matching eigenvalues in the same order.", formulas: ["eigendecomposition", "eigen-equation"], samples: [
    sample("Build Λ", "Eigenvalues are 4 and -1. Construct Λ.", ["Place eigenvalues on the diagonal.", "Put zeros off the diagonal."], "[[4,0],[0,-1]]", "Order must match eigenvector columns in C."),
    sample("Use a matrix power", "If A=CΛC⁻¹, express A³.", ["Multiply decompositions and cancel C⁻¹C.", "Cube the diagonal scale matrix."], "A³=CΛ³C⁻¹", "Diagonal powers are easy to calculate."),
    sample("Check diagonalizability", "A 2×2 matrix has only one independent eigenvector. Can C be inverted?", ["C would need two independent columns.", "One direction makes C singular."], "No", "Ordinary eigendecomposition fails without a full eigenbasis.")
  ]}),
  make(19, { id: "covariance-matrices-pca", title: "Covariance Matrices & PCA", prerequisites: ["eigendecomposition", "unit-vectors-normalization"], requiredTermIds: ["eigendecomposition", "unit-vectors-normalization"], term: "principal component", definition: "A unit direction chosen to capture as much remaining data variance as possible.", analogy: "The direction that best follows the long axis of a cloud", termExample: "A diagonal point cloud has its first principal component along that diagonal.", nonExample: "A principal component is not automatically one original feature column.", plain: "PCA finds eigenvectors of a covariance matrix and orders them by eigenvalues representing captured variance.", realTitle: "Photographing a long object", realBody: "Viewing a long object from the right direction preserves most of its visible length in a flat picture.", ml: "PCA compresses features, visualizes data, removes correlated redundancy, and can reduce noise.", wrong: "The largest eigenvalue identifies the most important original feature.", correction: "It identifies a direction combining features; inspect its eigenvector loadings to interpret it.", formulas: ["covariance", "eigen-equation", "eigendecomposition"], samples: [
    sample("Keep the main customer pattern", "A shop's centred customer data has covariance eigenvalues 9 and 1. Which learned direction should it keep first to make a one-number customer summary?", ["Treat each eigenvalue as variation captured along its eigenvector.", "Choose the eigenvector paired with the larger value, 9."], "The eigenvector for λ=9", "That direction preserves the strongest shared pattern in customer visits and spending."),
    sample("Measure information kept", "A photo-compression tool finds covariance eigenvalues 6, 3, and 1 for an image dataset. It keeps the first two principal directions. What fraction of visual variation remains?", ["Add the retained variation: 6+3=9.", "Add all variation: 6+3+1=10.", "Divide retained by total: 9/10."], "90%", "The compressed representation keeps 90% of the measured image variation and drops the smallest pattern first."),
    sample("Project a customer profile", "A business records three correlated customer measurements but keeps two principal components for a dashboard. What has it done to each customer profile?", ["Express each profile in the learned principal-direction basis.", "Keep the two coordinates carrying more variation.", "Drop the smallest-variation coordinate."], "Created a two-number customer summary", "Some detail is lost, but PCA deliberately drops the direction containing the least measured variation.")
  ]})
];
