import { sample, topic } from "../phase1Helpers.js";

const C = "linear-algebra";
const make = (order, config) => topic({ chapterId: C, order, ...config });

export const linearAlgebraLessons = [
  make(1, { id: "scalars-vectors-tensors", title: "Scalars, Vectors & Tensors", prerequisites: ["summation-subscripts-sets"], requiredTermIds: ["numbers-signs"], term: "scalar", definition: "One numerical value.", analogy: "One reading on a dashboard", termExample: "A student's attendance rate of 92% is one scalar.", nonExample: "[92, 78, 84] contains several ordered values, so it is not one scalar.", extraVocabulary: [
    ["vector", "vector", "An ordered list of numbers whose positions have defined meanings.", "One row of measurements describing one thing", "[92, 78, 84] could represent attendance, maths score, and English score for one student.", "An unordered collection of labels is not a numerical vector.", "Feature rows, embeddings, weights, and gradients are vectors."],
    ["tensor", "tensor", "A rectangular collection of numbers with one or more axes; scalars, vectors, and matrices are simpler cases.", "A stack of tables that can be stacked again", "A batch of 32 RGB images can have shape 32×3×224×224.", "A ragged list with inconsistent row lengths is not a rectangular tensor.", "Deep-learning inputs, parameters, and activations are stored as tensors."]
  ], plain: "Linear algebra begins with a simple idea: organize related numbers so we can operate on them together. One number is a scalar; one ordered row is a vector; more axes give matrices and higher-dimensional tensors.", realTitle: "One student becomes data", realBody: "Suppose a school records attendance, maths score, and English score. One score is a scalar. The three measurements for one student form a vector. The same measurements for a whole class form a table, and many classes over time form a higher-dimensional tensor.", ml: "Machine learning works by turning observations and model parameters into vectors and tensors, then transforming those organized numbers.", wrong: "A vector is just several numbers written next to each other.", correction: "The order and meaning of the components matter. Swapping two positions changes what the vector represents.", formulas: ["vector-notation"], samples: [
    sample("Build one student vector", "A student has attendance 90, maths 75, and English 80. Write the feature vector in that order.", ["Keep the stated component order.", "Place one measurement in each position."], "[90,75,80]", "The positions now have fixed meanings: attendance, maths, English."),
    sample("Move from one student to a class", "Five students each have three recorded features. What shape does the class table have if rows are students?", ["Rows count students: 5.", "Columns count features: 3."], "5×3", "The same vector structure is repeated for every student."),
    sample("Read an image tensor", "A model receives 32 RGB images of size 64×64. Interpret shape 32×3×64×64.", ["Read axes in order: batch, channels, height, width.", "Translate each axis into its role."], "32 images, 3 colour channels, each 64×64", "Tensor shape describes organization; the multiplication signs do not mean multiply these numbers together.")
  ]}),

  make(2, { id: "vector-arithmetic", title: "Vector Components & Arithmetic", prerequisites: ["scalars-vectors-tensors"], requiredTermIds: ["vector"], term: "vector arithmetic", definition: "Adding, subtracting, or scaling vectors by working with matching components.", analogy: "Updating the matching fields of one record together", termExample: "(2,3)+(4,1)=(6,4).", nonExample: "Adding a two-component vector to a three-component vector componentwise is not defined.", plain: "Once several quantities are packaged into a vector, we can change the whole object without losing the meaning of each position. Addition combines matching components; scalar multiplication applies the same scale to every component.", realTitle: "Following a route across campus", realBody: "Represent movement as [east, north]. Walking [3,2] and then [1,4] gives [4,6]. The vector lets two directions be updated together without treating them as unrelated numbers.", ml: "Training performs the same kind of arithmetic when a gradient vector is scaled by a learning rate and subtracted from a weight vector.", wrong: "Vector addition joins two lists end to end.", correction: "Vector addition combines matching positions, so the vectors must have compatible dimensions and component meanings.", formulas: ["vector-addition"], samples: [
    sample("Combine two movements", "You walk (3,2) and then (1,4). Find the total movement.", ["Add east components: 3+1.", "Add north components: 2+4."], "(4,6)", "You finish four units east and six units north of the start."),
    sample("Reverse and scale a direction", "Compute -2(3,-1).", ["Multiply each component by -2.", "Keep the component order."], "(-6,2)", "The negative sign reverses direction while the factor two doubles the length."),
    sample("Perform one learning update", "Weights are (5,2), gradient is (1,-3), and learning rate is 0.1. Compute w-0.1g.", ["Scale the gradient: 0.1(1,-3)=(0.1,-0.3).", "Subtract matching components from the weights."], "(4.9,2.3)", "Training updates many parameters at once using ordinary vector arithmetic.")
  ]}),

  make(3, { id: "vector-magnitude-distance", title: "Vector Magnitude & Distance", prerequisites: ["vector-arithmetic", "powers-roots-scientific"], requiredTermIds: ["vector", "powers-roots-scientific"], term: "magnitude", definition: "The non-negative Euclidean length of a vector.", analogy: "The length of an arrow regardless of the direction it points", termExample: "The vector (3,4) has magnitude 5.", nonExample: "Adding 3+4=7 does not give the Euclidean length of (3,4).", plain: "A vector tells both direction and components. Magnitude asks only how large the vector is. Distance between two points is found by subtracting their vectors and measuring the length of that difference.", realTitle: "How far apart are two profiles?", realBody: "Imagine two students represented only by two standardized measurements. Their coordinates may differ in both measurements at once. Euclidean distance compresses those differences into one straight-line separation.", ml: "k-NN and clustering compare feature vectors using distance; gradient clipping and regularization also depend on vector magnitude.", wrong: "A vector with negative components can have a negative magnitude.", correction: "Euclidean magnitude is a length, so it is never negative. Squaring removes component signs before the square root is taken.", formulas: ["vector-magnitude", "distance"], samples: [
    sample("Measure one movement", "Find ||(3,4)||₂.", ["Square the components: 9 and 16.", "Add them to get 25.", "Take √25."], "5", "The route components describe direction; magnitude gives the straight-line length."),
    sample("Measure separation", "Student A is at (1,2) and student B at (4,6) in a two-feature space. Find their Euclidean distance.", ["Subtract coordinates to get (3,4).", "Find the magnitude of that difference."], "5", "Both feature differences contribute to one distance score."),
    sample("Choose the nearest point", "Which point is closer to (0,0): (1,1) or (3,0)?", ["Their distances are √2 and 3.", "Compare the positive lengths."], "(1,1)", "A nearest-neighbour model would prefer the point with the smaller distance.")
  ]}),

  make(4, { id: "unit-vectors-normalization", title: "Unit Vectors & Normalization", prerequisites: ["vector-magnitude-distance"], requiredTermIds: ["vector", "vector-magnitude-distance"], term: "unit vector", definition: "A vector whose magnitude is exactly one.", analogy: "Keep the arrow's direction but trim or stretch it to one standard length", termExample: "(3/5,4/5) is the unit version of (3,4).", nonExample: "The zero vector cannot be normalized because its magnitude is zero.", plain: "Sometimes size is a distraction. Dividing a vector by its magnitude removes its original length while preserving direction. That lets us compare where vectors point rather than how large they happen to be.", realTitle: "Same direction, different strength", realBody: "Two people can walk in exactly the same direction even if one walks 2 km and the other 20 km. Converting both movements to unit vectors removes distance and keeps only direction.", ml: "Embedding systems often normalize vectors before similarity comparison so a larger raw vector does not win merely because of scale.", wrong: "Normalization means making the components add to one.", correction: "Euclidean vector normalization makes the vector's length one. That is different from converting numbers into probabilities that sum to one.", formulas: ["unit-vector", "vector-magnitude"], samples: [
    sample("Normalize a direction", "Normalize (3,4).", ["Its magnitude is 5.", "Divide every component by 5."], "(0.6,0.8)", "The arrow points exactly the same way but now has length one."),
    sample("Verify a unit vector", "Check that (1/√2,1/√2) has unit length.", ["Square both components to get 1/2 and 1/2.", "Add to 1, then take the square root."], "Magnitude 1", "The vector is a pure direction with no extra scale."),
    sample("Normalize an embedding", "An embedding is (0,10). Normalize it.", ["Magnitude is 10.", "Divide both coordinates by 10."], "(0,1)", "Its raw size disappears while its direction remains unchanged.")
  ]}),

  make(5, { id: "dot-product-angle", title: "Dot Product, Angle & Cosine", prerequisites: ["unit-vectors-normalization"], requiredTermIds: ["vector", "unit-vectors-normalization"], term: "dot product", definition: "A scalar found by multiplying matching vector components and adding those products.", analogy: "A score for how strongly one direction points along another", termExample: "(1,2)·(3,4)=1×3+2×4=11.", nonExample: "Returning (3,8) is componentwise multiplication, not a dot product.", plain: "The dot product turns two vectors into one number that reflects both their sizes and their alignment. Positive suggests similar direction, zero means perpendicular, and negative means opposing direction.", realTitle: "Does this recommendation match your interests?", realBody: "Represent a person's interests and an item's characteristics with matching components. Multiplying corresponding interests and features, then adding them, produces one compatibility score. Strong agreement contributes positively; opposing preferences can pull the score down.", ml: "Recommendation systems, linear models, neural layers, cosine similarity, vector search, and attention all build on dot products.", wrong: "A large raw dot product always means the vectors point in very similar directions.", correction: "Large magnitudes can inflate a dot product. Normalize first when you want direction-only similarity such as cosine similarity.", formulas: ["dot-product"], samples: [
    sample("Build one compatibility score", "Find (2,3)·(4,5).", ["Multiply matching components: 2×4=8 and 3×5=15.", "Add the contributions."], "23", "Two component-by-component agreements have become one scalar score."),
    sample("Recognize perpendicular directions", "Find (1,0)·(0,7).", ["Multiply matching components.", "Add 1×0 + 0×7."], "0", "A zero dot product here means the directions are perpendicular."),
    sample("Compare two products", "A user vector is (1,2). Product A=(2,1), product B=(-2,-1). Which aligns better?", ["User·A=1×2+2×1=4.", "User·B=1×(-2)+2×(-1)=-4.", "Compare the scores."], "Product A", "The positive score indicates alignment; the negative score points in the opposite preference direction.")
  ]}),

  make(6, { id: "matrix-anatomy-types", title: "Matrix Anatomy, Dimensions & Types", prerequisites: ["scalars-vectors-tensors"], requiredTermIds: ["vector"], term: "matrix", definition: "A rectangular arrangement of numbers organized into rows and columns.", analogy: "A spreadsheet where every row and column position has a mathematical role", termExample: "A 2×3 matrix has two rows and three columns.", nonExample: "Rows with different numbers of entries do not form a rectangular matrix.", plain: "A matrix lets many related vectors live in one object. Its shape is always rows × columns, and that shape tells us what the rows represent, what the columns represent, and which operations are possible.", realTitle: "The whole class in one table", realBody: "Return to the student example: each row is one student and each column is one feature such as attendance, maths, or English. A class of 100 students with 8 features becomes a 100×8 matrix.", ml: "Datasets, batches, weight collections, transformations, and covariance structures are naturally represented as matrices.", wrong: "A 2×3 matrix has two columns and three rows.", correction: "Matrix dimensions are always rows first, columns second.", formulas: ["matrix-shape"], samples: [
    sample("Read a class table", "What is the shape of [[1,2,3],[4,5,6]]?", ["Count rows: 2.", "Count entries in each row: 3."], "2×3", "Two records each contain three features."),
    sample("Recognize the identity matrix", "Classify [[1,0],[0,1]].", ["Check the diagonal entries.", "Check that all off-diagonal entries are zero."], "2×2 identity matrix", "Multiplying by the identity leaves a compatible vector unchanged."),
    sample("Interpret dataset shape", "X has shape 100×8 and rows are examples. Interpret X.", ["The first dimension counts examples.", "The second dimension counts features."], "100 examples and 8 features", "Shape is part of the meaning of the data, not only a storage detail.")
  ]}),

  make(7, { id: "matrix-vector-multiplication", title: "Matrix × Vector Multiplication", prerequisites: ["matrix-anatomy-types", "dot-product-angle"], requiredTermIds: ["matrix-anatomy-types", "dot-product-angle"], term: "matrix-vector product", definition: "A vector whose entries come from dotting each matrix row with the same input vector.", analogy: "Several scorecards asking different weighted questions about the same record", termExample: "A 2×3 matrix times a 3-vector produces a 2-vector.", nonExample: "Multiplying only the entries that happen to line up visually ignores the row-dot-vector rule.", plain: "This is where matrices stop being static tables. Each row acts like a vector of weights. Dot that row with the input, and you get one output. Many rows produce many outputs at once.", realTitle: "One student, two scorecards", realBody: "Suppose a student vector contains attendance, maths, and English. One row of weights can calculate an academic-support score while another row calculates an engagement score. Both rows inspect the same student vector but ask different weighted questions.", ml: "A dense neural-network layer does exactly this: every row of the weight matrix produces one neuron score from the same input vector.", wrong: "Any matrix can multiply any vector.", correction: "The number of matrix columns must equal the vector length, because every row needs one weight for each input component.", formulas: ["matrix-product", "linear-transform"], samples: [
    sample("Apply two scorecards", "Compute [[1,2],[0,1]](3,-1).", ["First row dot input: 1×3+2×(-1)=1.", "Second row dot input: 0×3+1×(-1)=-1."], "(1,-1)", "Two rows create two different outputs from one input vector."),
    sample("Check compatibility before calculating", "Can a 2×3 matrix multiply a length-2 vector?", ["The matrix has 3 columns.", "The vector supplies only 2 components.", "The inner dimensions do not match."], "No", "Checking dimensions first prevents meaningless arithmetic."),
    sample("Compute two neuron scores", "W=[[1,-1],[2,0]], x=(4,3). Find Wx.", ["Row one gives 4-3=1.", "Row two gives 8+0=8."], "(1,8)", "A two-row weight matrix produces two pre-activation neuron values.")
  ]}),

  make(8, { id: "matrix-matrix-multiplication", title: "Matrix × Matrix Multiplication", prerequisites: ["matrix-vector-multiplication"], requiredTermIds: ["matrix-vector-multiplication"], term: "matrix multiplication", definition: "An operation where each output entry is a dot product between one row of the first matrix and one column of the second.", analogy: "Running many compatible vector calculations together", termExample: "A 2×3 matrix times a 3×4 matrix produces a 2×4 matrix.", nonExample: "Multiplying entries in identical positions is the Hadamard product, not matrix multiplication.", plain: "Matrix-vector multiplication handles one vector. Matrix-matrix multiplication repeats that idea across many vectors or composes many transformations. The inner dimensions must match, and order matters because the operations have direction.", realTitle: "Score the whole class at once", realBody: "Instead of sending one student through two scorecards, place the entire class in a matrix and apply a compatible weight matrix. One multiplication can calculate the same set of scores for every student.", ml: "Batched predictions and stacked neural-network layers are efficient because matrix multiplication performs many dot products together.", wrong: "AB always equals BA.", correction: "Matrix multiplication is generally not commutative. Reversing the order changes the operation and may even make the multiplication impossible.", formulas: ["matrix-product"], samples: [
    sample("Multiply two small matrices", "Compute [[1,2],[0,1]][[2,0],[3,1]].", ["Row1·col1=1×2+2×3=8; row1·col2=1×0+2×1=2.", "Row2·col1=0×2+1×3=3; row2·col2=0×0+1×1=1."], "[[8,2],[3,1]]", "Each output entry is one familiar dot product."),
    sample("Predict the output shape", "A is 5×3 and B is 3×2. What is the shape of AB?", ["The inner dimensions 3 and 3 match.", "Keep the outer dimensions 5 and 2."], "5×2", "You can determine the output shape before calculating any entries."),
    sample("Process a batch", "X is 32×10 and W is 10×4. What is the shape of XW?", ["Ten input features match ten weight rows/columns as required by the chosen convention.", "Keep 32 batch rows and 4 output columns."], "32×4", "Thirty-two examples each receive four output values in one matrix operation.")
  ]}),

  make(9, { id: "transpose-symmetry", title: "Transpose & Symmetric Matrices", prerequisites: ["matrix-anatomy-types"], requiredTermIds: ["matrix-anatomy-types"], term: "transpose", definition: "The matrix formed by turning rows into columns and columns into rows.", analogy: "Look at the same table from the opposite orientation", termExample: "[[1,2],[3,4]]ᵀ=[[1,3],[2,4]].", nonExample: "Changing signs or reversing the order of values is not transposition.", plain: "Transpose does not change the values; it changes which axis they live on. That sounds minor, but it is how we align dimensions for dot products, covariance calculations, and many matrix formulas.", realTitle: "Students by subjects becomes subjects by students", realBody: "A grade matrix may have students as rows and subjects as columns. Transpose it and each subject becomes a row containing scores across students. The data is the same; the viewpoint changes.", ml: "Transposes appear throughout covariance, least squares, gradients, attention, and batched matrix operations because dimensions must line up correctly.", wrong: "Transpose means undo the matrix, like an inverse.", correction: "Transpose only swaps row and column indices. It does not reverse the transformation.", formulas: ["transpose"], samples: [
    sample("Transpose a table", "Transpose [[1,2,3],[4,5,6]].", ["Turn the first row into the first column.", "Turn the second row into the second column."], "[[1,4],[2,5],[3,6]]", "The shape changes from 2×3 to 3×2 without changing the six values."),
    sample("Recognize symmetry", "Is [[2,1],[1,3]] symmetric?", ["Transpose the matrix.", "Compare every entry with the original."], "Yes", "A symmetric matrix looks the same from the row and column viewpoints."),
    sample("Compare features with features", "X is 100×5. What is the shape of XᵀX?", ["Xᵀ has shape 5×100.", "Multiply 5×100 by 100×5."], "5×5", "The result has one row and column for each feature, which is why this pattern appears in feature relationships.")
  ]}),

  make(10, { id: "determinant-collapse", title: "Determinants & Geometric Collapse", prerequisites: ["matrix-matrix-multiplication"], requiredTermIds: ["matrix-anatomy-types"], term: "determinant", definition: "A signed number describing how a square matrix scales area or volume and whether it collapses dimensions.", analogy: "A meter showing how much space survives a transformation", termExample: "diag(2,3) has determinant 6, so it multiplies area by six.", nonExample: "In elementary linear algebra a determinant is not defined for a non-square matrix.", plain: "The determinant is useful because it answers a structural question before we try to undo a matrix: did the transformation preserve enough dimensional information? A nonzero determinant means area or volume survived; zero means at least one direction collapsed.", realTitle: "Stretch a sheet—or crush it into a line", realBody: "Imagine a square drawn on rubber. Stretching it changes its area but it is still a two-dimensional shape. Crush the entire sheet onto one line and its area becomes zero. The determinant detects that loss of dimension.", ml: "Determinants appear in invertibility, covariance and Gaussian formulas, and change-of-variable calculations where volume scaling matters.", wrong: "The determinant is just another way to add matrix entries.", correction: "For a 2×2 matrix it is ad-bc. That combination captures how the rows or columns interact as a transformation.", formulas: ["determinant"], samples: [
    sample("Measure surviving area", "Find det([[2,1],[3,4]]).", ["Use ad-bc.", "Compute 2×4-1×3=5."], "5", "The transformation keeps two-dimensional information and scales signed area by a factor of five."),
    sample("Detect a collapse", "Find det([[1,2],[2,4]]).", ["Compute 1×4-2×2.", "The result is zero."], "0", "The second row repeats the first direction, so the transformation cannot preserve a full 2D area."),
    sample("Interpret a negative determinant", "A 2D transformation has determinant -3. What does that tell you?", ["Absolute value 3 gives the area scale.", "The negative sign indicates an orientation flip."], "Area triples and orientation reverses", "Magnitude describes scale; sign describes orientation.")
  ]}),

  make(11, { id: "inverse-systems", title: "Matrix Inverses & Systems of Equations", prerequisites: ["determinant-collapse"], requiredTermIds: ["determinant-collapse"], term: "matrix inverse", definition: "A matrix that reverses the effect of an invertible square matrix.", analogy: "An undo button for a transformation that did not destroy information", termExample: "A⁻¹A=I returns a vector to where it started.", nonExample: "A square matrix with determinant zero has no inverse.", plain: "If a matrix transforms x into b, an inverse asks whether we can recover x from b. That is possible only when the original transformation kept enough information to distinguish different inputs.", realTitle: "Can we recover the original ingredients?", realBody: "Suppose two original quantities are mixed into two measured totals by a known rule. If the mixing rule keeps the two sources distinguishable, an inverse can recover the originals. If both measurements contain exactly the same information, recovery is impossible.", ml: "Linear-system solving appears in least squares and probabilistic models, although practical ML usually uses stable numerical solvers rather than explicitly calculating a matrix inverse.", wrong: "Invert a matrix by taking the reciprocal of every entry.", correction: "A matrix inverse is defined by AA⁻¹=I. Entrywise reciprocals generally do not satisfy that requirement.", formulas: ["matrix-inverse", "determinant"], samples: [
    sample("Undo two independent scalings", "For A=diag(2,4), propose A⁻¹.", ["Undo scaling by 2 with 1/2.", "Undo scaling by 4 with 1/4."], "diag(1/2,1/4)", "Applying A and then A⁻¹ restores both coordinates."),
    sample("Decide whether recovery is possible", "Can [[1,2],[2,4]] be inverted?", ["Its determinant is 4-4=0.", "Zero determinant means dimensional information was lost."], "No", "One row is just a scaled copy of the other, so two unknowns cannot be recovered uniquely."),
    sample("Solve a simple system", "Solve diag(2,5)x=(8,15).", ["The first coordinate satisfies 2x₁=8.", "The second satisfies 5x₂=15."], "x=(4,3)", "Inverse scaling recovers the original coordinates.")
  ]}),

  make(12, { id: "rank-column-null", title: "Rank, Column Space & Null Space", prerequisites: ["inverse-systems"], requiredTermIds: ["matrix-anatomy-types"], term: "rank", definition: "The number of independent output directions a matrix can produce.", analogy: "Count genuinely new information, not repeated copies", termExample: "Two proportional columns contribute only one independent column direction.", nonExample: "Rank is not simply the number of nonzero entries.", plain: "Rank tells us how much independent information survives a matrix. Column space describes the outputs the matrix can reach. Null space describes input directions that disappear completely into zero.", realTitle: "Two columns, but only one piece of information", realBody: "Imagine storing height in centimetres and also height in millimetres as two separate features. There are two columns, but the second is completely determined by the first. The dataset looks wider without actually gaining a new information direction.", ml: "Rank helps explain redundant features, multicollinearity, identifiability problems, low-rank compression, and information loss.", wrong: "Many nonzero entries automatically mean high rank.", correction: "Rows or columns can contain many nonzero numbers and still be exact combinations of one another.", formulas: ["rank-nullity"], samples: [
    sample("Spot duplicated direction", "Find the rank of [[1,2],[2,4]].", ["Row two is exactly twice row one.", "Only one independent row direction remains."], "Rank 1", "The matrix has two rows but only one independent information direction."),
    sample("Find something the matrix erases", "Find a nonzero v with [[1,2],[2,4]]v=0.", ["Solve x+2y=0.", "Choose y=1, giving x=-2."], "v=(-2,1)", "This entire input direction belongs to the null space and is collapsed to zero."),
    sample("Recognize redundant features", "Feature B is exactly 3× feature A. Does B increase the feature matrix rank?", ["B points in the same column direction as A.", "It adds no independent direction."], "No", "A wider matrix is not necessarily a more informative matrix.")
  ]}),

  make(13, { id: "linear-transformations", title: "Linear Transformations", prerequisites: ["matrix-vector-multiplication", "rank-column-null"], requiredTermIds: ["matrix-vector-multiplication"], term: "linear transformation", definition: "A mapping that preserves vector addition and scalar multiplication and can be represented by a matrix.", analogy: "A consistent rule that stretches, rotates, reflects, shears, or projects an entire grid", termExample: "T(x)=2x doubles every vector and preserves linear combinations.", nonExample: "T(x)=x+(1,1) is a translation and does not send zero to zero.", plain: "This is the central picture of linear algebra: a matrix is not merely a rectangle of numbers. It is a machine that moves every vector according to one consistent geometric rule.", realTitle: "Watch the whole coordinate grid move", realBody: "Draw a square grid on transparent plastic. A linear transformation may stretch it, rotate it, shear it, reflect it, or flatten it onto a line. Straight grid lines remain straight and the origin stays fixed.", ml: "Dense layers, projections, embeddings, PCA, and many convolution operations use linear transformations before nonlinear steps are applied.", wrong: "Any function that moves points is a linear transformation.", correction: "A linear map must preserve addition and scaling and therefore must map the zero vector to zero.", formulas: ["linear-transform", "matrix-product"], samples: [
    sample("Stretch two axes differently", "Apply diag(2,3) to (4,1).", ["Scale the first coordinate by 2.", "Scale the second coordinate by 3."], "(8,3)", "One transformation can stretch different directions by different amounts."),
    sample("Reject a translation", "Is T(x)=x+(1,1) linear?", ["Evaluate the zero input.", "T(0)=(1,1), not zero."], "No", "A translation moves the origin, so it fails a basic linearity requirement."),
    sample("Understand projection", "A transformation maps every (x,y) to (x,0). What is happening?", ["The x-coordinate survives.", "The y-coordinate is erased."], "Projection onto the x-axis", "The transformation keeps one direction and collapses the other into its null space.")
  ]}),

  make(14, { id: "basis-coordinates", title: "Standard Basis & Coordinates", prerequisites: ["linear-transformations"], requiredTermIds: ["vector", "linear-transformations"], term: "basis", definition: "A set of independent vectors that can build every vector in a space uniquely.", analogy: "Choose the measuring directions used to describe every location", termExample: "(1,0) and (0,1) form the standard basis of 2D space.", nonExample: "(1,0) and (2,0) cannot form a 2D basis because both point along the same line.", plain: "A vector exists independently of the coordinate numbers we write for it. Coordinates are instructions saying how much of each chosen basis direction is needed to build that vector.", realTitle: "Describe one journey using two compass directions", realBody: "We usually describe movement using east and north. But we could choose northeast and southeast as our two independent directions instead. The physical destination would stay the same; only the coordinate description would change.", ml: "Feature vectors and embeddings are coordinate descriptions in some representation space, and PCA deliberately learns a new basis for the data.", wrong: "A vector and its coordinate list are always the same thing.", correction: "Coordinates depend on the chosen basis. Change the basis and the numbers can change even though the underlying vector does not.", formulas: ["basis-coordinates"], samples: [
    sample("Use the standard basis", "Write (4,-2) using e₁=(1,0), e₂=(0,1).", ["Take four copies of e₁.", "Take negative two copies of e₂."], "4e₁-2e₂", "The familiar pair (4,-2) is already a coordinate description in the standard basis."),
    sample("Check whether two directions form a basis", "Do (1,1) and (1,-1) form a basis for 2D?", ["They are not scalar multiples of one another.", "Two independent vectors can span the 2D plane."], "Yes", "Independence gives a unique way to build every 2D vector."),
    sample("Build a vector from nonstandard coordinates", "Using b₁=(1,1), b₂=(1,-1), build the vector with coordinates [1,1].", ["Compute 1b₁+1b₂.", "Add (1,1)+(1,-1)."], "(2,0)", "Coordinates [1,1] do not mean the standard vector (1,1) when the basis has changed.")
  ]}),

  make(15, { id: "change-of-basis", title: "Change of Basis", prerequisites: ["basis-coordinates", "inverse-systems"], requiredTermIds: ["basis-coordinates", "inverse-systems"], term: "change of basis", definition: "Re-expressing the same vector or transformation using a different basis.", analogy: "Describe the same journey using a different pair of compass axes", termExample: "Vector (2,0) has coordinates (1,1) in basis {(1,1),(1,-1)}.", nonExample: "Physically rotating a vector is a transformation, not merely a change in description.", plain: "Change of basis is a change of language, not a change of object. We choose coordinates that make the structure easier to see or the calculation easier to perform.", realTitle: "The destination stays put while the coordinate system rotates", realBody: "A pilot, a map, and a runway may use different reference directions to describe the same motion. Converting coordinates lets all three describe the same physical vector without moving it.", ml: "PCA is powerful largely because it chooses a new basis aligned with directions of variation in the data.", wrong: "If the coordinates changed, the vector must have moved.", correction: "During a pure basis change only the representation changes; the underlying geometric vector stays the same.", formulas: ["change-basis", "basis-coordinates"], samples: [
    sample("Describe the same vector differently", "Find the coordinates of (2,0) in b₁=(1,1), b₂=(1,-1).", ["Solve c₁+c₂=2.", "Solve c₁-c₂=0, giving c₁=c₂=1."], "(1,1)", "The coordinates changed from (2,0) to (1,1), but both descriptions produce the same vector."),
    sample("Return to standard coordinates", "Convert basis coordinates (3,1) using b₁=(1,1), b₂=(1,-1).", ["Compute 3b₁+b₂.", "Add (3,3)+(1,-1)."], "(4,2)", "The basis vectors translate a coordinate description back into the ordinary plane."),
    sample("Interpret a PCA coordinate", "What does one PCA coordinate tell you?", ["Identify the learned principal direction.", "Measure how far the data vector projects along that direction."], "The amount of the data vector along one principal component", "PCA stores data in a learned coordinate system rather than the original feature axes.")
  ]}),

  make(16, { id: "composition-matrix-powers", title: "Composition & Matrix Powers", prerequisites: ["matrix-matrix-multiplication", "linear-transformations"], requiredTermIds: ["matrix-matrix-multiplication", "linear-transformations"], term: "composition", definition: "Applying one transformation and then another, represented by matrix multiplication.", analogy: "Pass an object through several processing stages in sequence", termExample: "BAx means apply A to x first, then B.", nonExample: "A+B combines matrix effects algebraically but does not mean apply A and then B.", plain: "Once matrices are transformations, matrix multiplication becomes easy to interpret: multiplication composes stages. Matrix powers simply repeat the same transformation again and again.", realTitle: "An image-processing pipeline", realBody: "Imagine one linear step resizes coordinates and another rotates them. The image point experiences the resize first and then the rotation. Their matrix product packages both stages into one transformation.", ml: "Layer stacks, recurrent state updates, Markov processes, and iterative algorithms repeatedly compose transformations.", wrong: "In ABx, A acts first because A is written first.", correction: "Operations act on x from the right: B acts first in ABx, then A acts on the result.", formulas: ["matrix-powers", "matrix-product"], samples: [
    sample("Repeat one scaling twice", "For A=diag(2,2), find A².", ["Each application doubles both coordinates.", "Two applications multiply the scale factors: 2×2=4."], "diag(4,4)", "A² summarizes two identical transformations in one matrix."),
    sample("Repeat a transformation three times", "If A=2I, what is A³?", ["Each use multiplies every coordinate by 2.", "Three uses give 2³."], "8I", "Matrix powers compactly describe repeated linear dynamics."),
    sample("Read layer order", "If h=Ax and y=Bh, write y directly in terms of x.", ["Substitute h=Ax into y=Bh.", "Keep the order B(Ax)."], "y=BAx", "The transformation applied later appears on the left in the matrix product.")
  ]}),

  make(17, { id: "eigenvalues-eigenvectors", title: "Eigenvalues & Eigenvectors", prerequisites: ["determinant-collapse", "linear-transformations"], requiredTermIds: ["determinant-collapse", "linear-transformations"], term: "eigenvector", definition: "A nonzero vector whose direction line is preserved by a linear transformation; the vector is only scaled or reversed.", analogy: "A special direction that a transformation can stretch without turning away from itself", termExample: "For diag(3,2), (1,0) is an eigenvector with eigenvalue 3.", nonExample: "The zero vector is excluded because every scale factor would fit it and therefore reveal no special direction.", plain: "Most vectors change both length and direction under a transformation. Eigenvectors are the exceptional directions that do not turn. Their eigenvalues tell what the transformation does along those directions.", realTitle: "Find the natural stretch directions of a rubber sheet", realBody: "Stretch a patterned rubber sheet unevenly. Many printed arrows tilt as the sheet deforms, but some directions remain pointing along their original line. Those preserved directions behave like eigenvectors; the amount of stretch along them behaves like the eigenvalue.", ml: "Eigenvectors and eigenvalues appear in PCA, spectral clustering, covariance analysis, stability, and repeated transformations.", wrong: "Every vector is an eigenvector of a matrix.", correction: "Only special nonzero directions that remain on their own line after transformation qualify.", formulas: ["eigen-equation", "characteristic-equation"], samples: [
    sample("Verify one natural direction", "For A=diag(3,2), verify v=(1,0) with λ=3.", ["Compute Av=(3,0).", "Compute 3v=(3,0).", "Compare both sides."], "Av=3v, so the pair is valid", "The x-axis direction survives unchanged while its length triples."),
    sample("Read eigenvalues of a diagonal transform", "Find the eigenvalues of diag(5,-2).", ["Each coordinate axis already remains on itself.", "Read the scale factor applied on each axis."], "5 and -2", "The negative eigenvalue means one eigen-direction reverses while being scaled by two."),
    sample("Interpret eigenvalue zero", "What happens when an eigenvector has λ=0?", ["Use Av=λv.", "Then Av=0v=0."], "That eigen-direction collapses to zero", "A zero eigenvalue reveals a direction in which the transformation loses information.")
  ]}),

  make(18, { id: "eigendecomposition", title: "Eigendecomposition", prerequisites: ["eigenvalues-eigenvectors", "change-of-basis"], requiredTermIds: ["eigenvalues-eigenvectors", "change-of-basis"], term: "eigendecomposition", definition: "Factoring a diagonalizable matrix into a change to eigenvector coordinates, independent scaling by eigenvalues, and a change back.", analogy: "Move into the transformation's natural directions, do easy independent stretches, then return", termExample: "A=CΛC⁻¹ stores eigenvectors in C and their matching eigenvalues on Λ's diagonal.", nonExample: "Not every matrix has enough independent eigenvectors to form this decomposition.", plain: "Eigendecomposition connects several earlier ideas at once: basis, change of basis, eigenvectors, and matrix multiplication. A complicated transformation becomes simple when viewed in the right coordinate system.", realTitle: "Turn a complicated stretch into simple axis-by-axis scaling", realBody: "A transformation may look like a mixture of rotation and stretching in ordinary x-y coordinates. In its eigenvector basis, the same transformation can become a diagonal matrix: each special direction is scaled independently with no mixing.", ml: "This viewpoint explains PCA and simplifies matrix powers, spectral methods, covariance analysis, and linear dynamical systems.", wrong: "C contains eigenvalues and Λ contains eigenvectors.", correction: "The columns of C are eigenvectors. The matching eigenvalues sit on the diagonal of Λ in the same order.", formulas: ["eigendecomposition", "eigen-equation"], samples: [
    sample("Build the easy scaling matrix", "Eigenvalues are 4 and -1. Construct Λ.", ["Place the eigenvalues on the diagonal.", "Put zeros in the off-diagonal positions."], "[[4,0],[0,-1]]", "In eigenvector coordinates, the transformation is just independent scaling along two directions."),
    sample("Use the decomposition for repeated transformation", "If A=CΛC⁻¹, express A³.", ["Write three copies of the decomposition.", "Adjacent C⁻¹C terms cancel to I.", "Only the diagonal scaling needs to be cubed."], "A³=CΛ³C⁻¹", "The difficult repeated matrix operation becomes an easy power of diagonal eigenvalues."),
    sample("Recognize when ordinary eigendecomposition fails", "A 2×2 matrix has only one independent eigenvector. Can its eigenvector matrix C be inverted?", ["C would need two independent columns.", "One independent eigenvector makes C singular."], "No", "Without a full eigenvector basis, the ordinary CΛC⁻¹ decomposition is unavailable.")
  ]}),

  make(19, { id: "covariance-matrices-pca", title: "Covariance Matrices & PCA", prerequisites: ["eigendecomposition", "unit-vectors-normalization"], requiredTermIds: ["eigendecomposition", "unit-vectors-normalization"], term: "principal component", definition: "A unit direction chosen to capture as much remaining data variance as possible.", analogy: "Turn the coordinate axes until one axis follows the longest direction of the data cloud", termExample: "A diagonal point cloud has its first principal component along that diagonal.", nonExample: "A principal component is not necessarily one of the original feature columns.", plain: "PCA is where the linear-algebra story comes together. Build a covariance matrix, find its eigenvectors, rank them by eigenvalue, then describe each data point in that new basis. The first directions preserve the most variation.", realTitle: "Compress a class dataset without keeping every original column", realBody: "Suppose student attendance, assignment completion, and several assessment measures move together. Plotting the data may reveal a long cloud rather than independent axes. PCA rotates the coordinate system toward that cloud so a smaller number of coordinates can preserve much of the measured variation.", ml: "PCA is used for dimensionality reduction, visualization, decorrelation, compression, and sometimes noise reduction before downstream modelling.", wrong: "The largest eigenvalue identifies the single most important original feature.", correction: "It identifies a direction that can combine several original features. Interpret the eigenvector loadings to understand that direction.", formulas: ["covariance", "eigen-equation", "eigendecomposition"], samples: [
    sample("Keep the strongest direction", "A centred dataset has covariance eigenvalues 9 and 1. Which principal direction should be kept first for a one-number summary?", ["Each covariance eigenvalue measures variance captured along its eigenvector.", "Choose the eigenvector paired with the larger eigenvalue, 9."], "The eigenvector for λ=9", "That direction preserves the strongest pattern of variation in the dataset."),
    sample("Measure how much variation is retained", "Covariance eigenvalues are 6, 3, and 1. If PCA keeps the first two principal components, what fraction of total variance remains?", ["Retained variance is 6+3=9.", "Total variance is 6+3+1=10.", "Divide 9 by 10."], "90%", "Two new coordinates retain 90% of the measured variation while discarding the weakest direction."),
    sample("Understand the compressed representation", "A dataset has three correlated features but PCA keeps two principal components. What happens to each data point?", ["Express the point in the learned principal-component basis.", "Keep the two coordinates associated with larger eigenvalues.", "Drop the coordinate carrying the least variance."], "Each point becomes a two-number representation", "PCA deliberately trades some information for a lower-dimensional representation that preserves the dominant structure.")
  ]})
];
