// Guided teaching material is separate from the preserved levels, labs, and exercises.
import { mcq } from "./schema.js";

const word = (id, name, definition, analogy, example, nonExample) => ({ id, name, definition, analogy, example, nonExample });
const notation = (expression, readAs, symbols) => ({ expression, readAs, symbols });
const example = (title, prompt, pairs, answer, interpretation) => ({
  title, prompt, walkthrough: pairs.map(([action, reason]) => ({ action, reason })),
  steps: pairs.map(([action, reason]) => `${action} ${reason}`), answer, interpretation
});
const question = (id, prompt, options, answerIndex, explanation) => mcq(`guided-${id}`, prompt, options, answerIndex, explanation, "concept");

export const DEEP_LEARNING_GUIDES = {
  "tensors-perceptrons": {
    goal: "Organize inputs and calculate one weighted score before building a whole layer.",
    introduction: "A tensor is an organized block of numbers with named axes, such as rows for orders and columns for items. A weight controls an input's influence; a bias is a starting score. A perceptron adds weighted inputs and a bias, then uses a cutoff to choose a category. An activation is a rule that turns a score into a unit's output. A dense layer repeats a weighted calculation for several units, each connected to every input.",
    concepts: ["Keep the meaning of each axis visible: two orders with three features form a 2 by 3 tensor.", "Positive weights raise a score; negative weights lower it. A dense layer can produce several scores for each order."],
    vocabulary: [word("tensor", "tensor", "A block of numbers organized along axes; a scalar has zero axes, a vector one, and a matrix two.", "A spreadsheet, or a stack of spreadsheets", "Two orders with three measurements have shape 2 by 3.", "A shape without numbers or axis meanings.")],
    scenario: { title: "Score a delivery job", body: "A courier earns 3 points per parcel, loses 1 point per kilometre, and starts with 2 points. For 2 parcels and 1 kilometre, each quantity has its own influence." },
    everydayExample: example("A weighted delivery score", "Score 2 parcels and 1 kilometre using weights 3 and −1, plus starting score 2.", [["Multiply 2 × 3 = 6 and 1 × (−1) = −1.", "This converts each input into its point contribution."], ["Add 6 − 1 + 2 = 7.", "Combining the contributions and starting score gives the total."]], "7 points", "The negative distance weight offsets some of the parcel contribution."),
    mlExample: example("Two orders through one unit", "Rows [2,1] and [1,2] use weights [3,−1] and bias 2.", [["Compute 2 × 3 − 1 + 2 = 7 for the first row.", "Each row is a separate model input."], ["Compute 1 × 3 − 2 + 2 = 3 for the second row.", "Reusing the same weights applies the same learned rule to both orders."]], "Scores [7,3], shape 2 by 1", "Two examples produce one score each; these scores are not automatically probabilities."),
    task: "Compute a score for each delivery using the same learned weights and bias.",
    notation: notation("z = w₁x₁ + w₂x₂ + b", "Multiply each input by its weight, add the results, then add the bias.", [["x₁, x₂", "Parcel count and distance: 2 and 1."], ["w₁, w₂", "Influences: 3 and −1."], ["b", "Starting score: 2."], ["z", "Score before an activation: 7."]]),
    questions: [question("tensor-story", "What does the weight −1 do to the distance contribution?", ["Lowers the score", "Always raises it", "Deletes the parcel count"], 0, "Each kilometre contributes −1 point."), question("tensor-try", "Three examples each have two features. What is the input shape?", ["2 by 3", "3 by 2", "3 by 3"], 1, "There is one row per example and two feature columns."), question("tensor-ml", "Why reuse the same weights for both orders?", ["To guarantee equal scores", "To apply the same prediction rule", "To remove all inputs"], 1, "The inputs differ, but the model's learned rule is shared.")],
    misconception: { wrong: "Every tensor is a matrix.", correction: "A matrix has two axes. Tensors can also have zero, one, or more than two axes." }
  },
  "activations-losses": {
    goal: "Separate a unit's response rule from the score used to judge a prediction.",
    introduction: "An activation is a function that turns a unit's input score into an output. ReLU, short for rectified linear unit, keeps positive scores and replaces negative ones with zero. A loss is a number measuring how poor a prediction is. An activation shapes the response; a loss judges that response against a target.",
    concepts: ["Nonlinear means the response cannot be described by one straight line. ReLU bends at zero, letting stacked layers learn more than one straight-line rule.", "Sigmoid turns one score into a number between 0 and 1. Softmax turns several scores into positive weights summing to 1. Cross-entropy is a loss that penalizes low probability for the correct class."],
    vocabulary: [word("activation", "activation", "A function applied to a unit's score to produce its output.", "A controller deciding how strongly a heater responds", "ReLU turns −2 into 0 and keeps 3 as 3.", "The loss that compares a prediction with its target.")],
    scenario: { title: "A heater cannot supply negative heat", body: "A heater's requested settings are −2, 0, and 3 units. Its controller replaces negative requests with zero while keeping positive requests." },
    everydayExample: example("Clip the heating request", "Apply the heater rule to requests [−2,0,3].", [["Replace −2 with 0.", "The heater cannot deliver negative heat."], ["Keep 0 and 3.", "These requests already satisfy the nonnegative rule."]], "[0,0,3]", "The response rule has a bend at zero."),
    mlExample: example("Output and loss are different numbers", "A unit has score −2, uses ReLU, and should predict target 1. Use squared error as the loss.", [["Apply ReLU: max(0,−2) = 0.", "The activation determines the prediction."], ["Compute (0 − 1)² = 1.", "The squared difference measures how far that prediction misses the target."]], "Prediction 0; loss 1", "Changing the activation changes the output; changing the loss changes how we judge errors."),
    task: "Turn a unit's score into a prediction and compare it with a known target.",
    notation: notation("a = max(0,z); L = (a − y)²", "Keep the larger of zero and the score, then square the difference from the target.", [["z", "The input score, −2."], ["a", "The activated output, 0."], ["y", "The target, 1."], ["L", "Squared-error loss, 1."]]),
    questions: [question("activation-story", "What does ReLU return for −4?", ["−4", "4", "0"], 2, "Negative scores become zero."), question("activation-try", "Output 3, target 1: what is squared-error loss?", ["2", "4", "3"], 1, "The difference is 2; squaring gives 4."), question("activation-ml", "Which quantity judges prediction quality?", ["Loss", "Input shape", "Number of rows"], 0, "Loss compares the prediction with the desired answer.")],
    misconception: { wrong: "Every activation returns a probability.", correction: "ReLU can return values above 1. The output rule must match the task." }
  },
  "forward-backprop": {
    goal: "Trace a prediction forward and calculate how a small weight change affects its loss.",
    introduction: "Forward propagation means computing values from inputs to prediction and loss, a score of prediction error. A derivative measures how fast one quantity changes with another. Backpropagation calculates these change rates backward through the operations using the chain rule: multiply change rates along a path and add contributions from different paths. A gradient collects change rates for the adjustable parameters.",
    concepts: ["Backpropagation computes gradients. An optimizer, the rule for adjusting parameters, uses them afterward.", "Intermediate values from the forward calculation help evaluate the backward calculation at the current inputs and weights."],
    vocabulary: [word("backpropagation", "backpropagation", "Computing loss change rates backward through a calculation using local derivatives.", "Tracing how a recipe adjustment affects the final result", "If two local change rates are 2 and 3, their chain contributes 6.", "Updating a weight before calculating its gradient.")],
    scenario: { title: "Recipe portions and cost", body: "Each tray uses 2 scoops of flour, and each scoop costs 3 coins. Changing the number of trays changes scoops first and cost next." },
    everydayExample: example("Trace the cost of one more tray", "There are 2 scoops per tray and 3 coins per scoop.", [["One extra tray needs 2 extra scoops.", "This measures the first link in the chain."], ["Multiply 2 scoops by 3 coins = 6 coins.", "Combining the two rates gives the cost change per tray."]], "6 coins per extra tray", "Rates along successive operations multiply."),
    mlExample: example("Differentiate a tiny model", "Input x=2, weight w=3, target y=5; prediction a=wx and loss L=(a−y)².", [["Compute a = 3 × 2 = 6 and L = (6 − 5)² = 1.", "The forward pass gives the values needed by the derivatives."], ["The loss changes at rate 2(a−y) = 2; a changes at rate x = 2 with w.", "Each rate describes one operation at the current values."], ["Multiply 2 × 2 = 4.", "The chain rule gives the loss change rate with respect to w."]], "dL/dw = 4", "A small decrease in w lowers this loss locally; backpropagation itself has not changed w."),
    task: "Find the weight gradient for a model predicting a numerical target.",
    notation: notation("dL/dw = (dL/da)(da/dw)", "Multiply the loss change per output change by the output change per weight change.", [["L", "Loss, here (a−5)²."], ["a", "Prediction, here 2w."], ["w", "Adjustable weight, currently 3."], ["dL/dw", "Local loss change per unit weight change, here 4."]]),
    questions: [question("backprop-story", "Two scoops per tray and 3 coins per scoop gives what rate?", ["5 coins per tray", "6 coins per tray", "1 coin per tray"], 1, "Multiply rates along the chain: 2 × 3 = 6."), question("backprop-try", "Local derivatives are 2 and 0.5. What is their chain product?", ["1", "2.5", "4"], 0, "Multiplication gives 1; a small local rate can shrink the signal."), question("backprop-ml", "Does calculating a gradient automatically update the weight?", ["Yes", "No, an optimizer uses it afterward"], 1, "The derivative calculation and parameter update are separate operations.")],
    misconception: { wrong: "Backpropagation is the weight update.", correction: "It calculates gradients; the optimizer decides how to change the weights." }
  },
  "deep-optimization-regularization": {
    goal: "Take a controlled training step and distinguish improving training loss from improving unseen-data performance.",
    introduction: "An optimizer is a rule for adjusting a model's parameters, its learnable numbers. Initialization chooses their starting values. Regularization constrains learning to discourage fitting training details too closely. Validation data are held-out examples used to compare model choices. Overfitting means doing well on training examples but poorly on new ones.",
    concepts: ["A gradient measures local loss change. The learning rate controls the size of a step against that gradient. Momentum carries information from past gradients; Adam also rescales updates using gradient history.", "Weight decay pulls weights toward zero. Dropout temporarily sets some unit outputs to zero during training. Early stopping keeps a model from an earlier training stage when validation performance was better.", "Identically initialized hidden units with identical connections receive the same signals and cannot learn different roles. Small random starting weights break this symmetry."],
    vocabulary: [word("regularization", "regularization", "A constraint or penalty used to discourage overfitting.", "Practising varied questions instead of memorizing one answer sheet", "Compare validation loss when choosing weight decay.", "Selecting settings from the final test answers.")],
    scenario: { title: "Adjust a practice routine gradually", body: "A coach starts with a practice setting of 3. Feedback says the error increases at 4 units per extra setting unit. The coach chooses a cautious step size of 0.1." },
    everydayExample: example("Use feedback to adjust a setting", "Setting 3, local error-change rate 4, step size 0.1.", [["Compute 0.1 × 4 = 0.4.", "Scaling the feedback limits the adjustment."], ["Subtract 0.4 from 3 to get 2.6.", "Moving against a positive change rate aims to reduce error locally."]], "New setting 2.6", "A cautious step follows feedback; later checks still determine whether it helped."),
    mlExample: example("Update, then compare validation", "Weight 3 has gradient 4 and learning rate 0.1. Model A has training/validation losses 0.1/0.8; regularized model B has 0.2/0.3.", [["Update the weight: 3 − 0.1 × 4 = 2.6.", "Gradient descent uses local loss feedback to change a parameter."], ["Compare validation losses 0.8 and 0.3; prefer B in this comparison.", "Held-out results matter more for selection than the lowest training loss."]], "Weight 2.6; select B for its lower validation loss", "Regularization may raise training loss while improving performance on held-out data."),
    task: "Control a training update and select a regularization setting using validation loss.",
    notation: notation("w_new = w − ηg", "Subtract learning rate times gradient from the current weight.", [["w", "Current weight, 3."], ["η", "Learning rate, 0.1."], ["g", "Current loss gradient, 4."], ["w_new", "Updated weight, 2.6."]]),
    questions: [question("deepopt-story", "How large is the adjustment 0.1 × 4?", ["0.4", "4.1", "40"], 0, "The small step size scales the feedback to 0.4."), question("deepopt-try", "Weight 2, gradient 3, learning rate 0.1: new weight?", ["2.3", "1.7", "0.6"], 1, "Subtract 0.1 × 3 from 2."), question("deepopt-ml", "Which result should guide regularization choices?", ["Training loss alone", "Validation performance", "Final test answers used repeatedly"], 1, "Validation data compare settings while preserving the test set for the final evaluation.")],
    misconception: { wrong: "The lowest training loss always identifies the best model.", correction: "Compare held-out performance; a model can memorize training data and fail on new examples." }
  },
  "cnn-convolution": {
    goal: "Slide one small weighted pattern across data and calculate its outputs.",
    introduction: "Convolution in a neural network applies the same small set of weights to neighbouring inputs at successive positions. This set is called a kernel or filter. Its output at each position forms a feature map. A convolutional neural network (CNN) uses these operations to learn patterns such as edges. Neural-network libraries usually use the unflipped-kernel operation, technically cross-correlation, under the name convolution.",
    concepts: ["Stride is the number of positions moved between applications. Padding adds border values so the filter can cover boundary positions.", "A channel is one kind of measurement at each position, such as red intensity. Reusing weights detects a pattern wherever the filter is applied; it does not guarantee rotation invariance."],
    vocabulary: [word("convolution", "convolution", "In a CNN, sliding shared filter weights over local inputs and adding weighted contributions.", "Sliding the same inspection window along a shelf", "Weights [1,−1] on [2,5] give −3.", "Learning an unrelated filter for every location.")],
    scenario: { title: "Compare neighbouring shelf counts", body: "Three adjacent shelves hold 2, 5, and 4 items. An inspector applies the same rule to each neighbouring pair: left count minus right count." },
    everydayExample: example("Slide a two-shelf window", "Counts [2,5,4], weights [1,−1], move one shelf at a time.", [["Apply the rule to [2,5]: 2 × 1 + 5 × (−1) = −3.", "The negative result says the right shelf has more items."], ["Slide to [5,4]: 5 × 1 + 4 × (−1) = 1.", "The same weights compare the next pair consistently."]], "[−3,1]", "One rule finds local changes at two positions."),
    mlExample: example("Detect changes in a short image row", "Pixel intensities [2,5,4], filter [1,−1], stride 1, padding 0.", [["Calculate 2 − 5 = −3 and 5 − 4 = 1.", "The shared filter measures local brightness changes."], ["Count 3 − 2 + 1 = 2 valid placements.", "Only windows fully inside the row are used without padding."]], "Feature map [−3,1], width 2", "A learned filter can respond to local patterns throughout an image."),
    task: "Use a shared filter to detect brightness changes across neighbouring pixels.",
    notation: notation("oᵢ = k₁xᵢ + k₂xᵢ₊₁", "At each position, multiply the neighbouring inputs by the same two filter weights and add.", [["i", "Starting position of the window."], ["xᵢ, xᵢ₊₁", "Neighbouring pixel values."], ["k₁, k₂", "Shared weights 1 and −1."], ["oᵢ", "Output at that position."]]),
    questions: [question("cnn-story", "What does the filter [1,−1] return for [5,4]?", ["9", "−1", "1"], 2, "Multiply matching entries and add: 5 − 4 = 1."), question("cnn-try", "Width 5, filter width 3, stride 1, no padding: how many placements fit?", ["3", "5", "1"], 0, "The starting positions are 1, 2, and 3: 5 − 3 + 1 = 3."), question("cnn-ml", "Why use the same filter at each position?", ["To detect the same local pattern", "To guarantee every output is equal", "To remove all input data"], 0, "Shared weights apply one pattern detector throughout the input.")],
    misconception: { wrong: "Convolution makes every image transformation irrelevant.", correction: "Sharing a filter reuses a local detector across positions; rotation and other changes can still alter the output." }
  },
  "sequence-models": {
    goal: "Represent ordered items as numbers and update a running memory one item at a time.",
    introduction: "A sequence is an ordered list, such as words in a sentence. A token is one item used by a text model, often a word or part of a word. An embedding is a learned vector of numbers representing an item. A recurrent neural network (RNN) reads each item and updates a hidden state, its running numerical summary. A long short-term memory network (LSTM) adds a memory store and gates, learned controls for retaining or changing information.",
    concepts: ["Embedding lookup selects the vector for an item; the item's ID is an address, not a measure of meaning.", "An RNN reuses its update rule at every position. Order matters because the next state depends on both the current item and the previous state.", "An LSTM gate uses values between 0 and 1 to control information flow. This helps manage memory, but does not guarantee perfect recall."],
    vocabulary: [word("embedding", "embedding", "A learned vector used to represent an item for model calculations.", "A numerical description card for each item", "A token ID selects one row of an embedding table.", "Treating token ID 20 as twice the meaning of ID 10.")],
    scenario: { title: "Keep a running shopping total", body: "You see purchases costing 2 coins, then 3 coins. Start with a total of 0 and update it after each item instead of storing only the last price." },
    everydayExample: example("Update a running memory", "Start at 0; purchases cost 2 then 3 coins.", [["Add the first price: 0 + 2 = 2.", "The running total now remembers the first purchase."], ["Add the second price: 2 + 3 = 5.", "The previous total carries earlier information into the next update."]], "5 coins", "A running state summarizes earlier items; a total alone does not preserve their order."),
    mlExample: example("A toy recurrent update", "Use scalar embedding values x₁=2, x₂=3; start h₀=0 and update hₜ=0.5hₜ₋₁+xₜ.", [["Compute h₁ = 0.5 × 0 + 2 = 2.", "The first state combines initial memory with the first item."], ["Compute h₂ = 0.5 × 2 + 3 = 4.", "The second state retains half the earlier state and adds the current item."], ["Reverse the inputs: h₁=3, then h₂=0.5 × 3 + 2=3.5.", "This checks that this update distinguishes order, unlike an ordinary sum."]], "Final state 4; reversed order gives 3.5", "This simplified linear recurrence illustrates memory; a full RNN also applies an activation, a function shaping the unit's output."),
    task: "Encode ordered inputs into a running representation for a sequence prediction.",
    notation: notation("hₜ = 0.5hₜ₋₁ + xₜ", "Keep half the previous state and add the current input.", [["t", "Position in the sequence."], ["xₜ", "Current scalar input representation."], ["hₜ₋₁", "State from the previous position."], ["hₜ", "Updated state; this is a toy recurrence."]]),
    questions: [question("sequence-story", "Why carry the previous total into the next update?", ["To remember earlier purchases", "To discard all earlier prices", "To sort prices alphabetically"], 0, "The state preserves information from earlier items."), question("sequence-try", "Previous state 4 and input 1: what is 0.5 × 4 + 1?", ["5", "3", "2"], 1, "Retain 2 from the old state and add 1."), question("sequence-ml", "What does an embedding lookup retrieve?", ["A learned vector for an item", "The final answer to every task", "The item's alphabetical rank"], 0, "The ID selects a numerical representation that training can adjust.")],
    misconception: { wrong: "An item ID measures how much meaning the item has.", correction: "The ID selects an embedding row. The learned numbers in that row are the representation." }
  },
  "attention-transformers": {
    goal: "Calculate a weighted mixture of relevant information and explain its role in a transformer.",
    introduction: "An embedding is a learned vector representing an item. Attention scores how relevant available items are to a request and uses weights to mix their information. A query represents the request, a key is what it is matched against, and a value holds the information to combine. A transformer is a neural network built from repeated attention and per-item processing stages, with position information to represent order.",
    concepts: ["Softmax converts matching scores into positive weights summing to 1. Larger scores receive larger weights. A dot product multiplies matching vector entries and adds them to give a matching score.", "Self-attention forms queries, keys, and values from the same sequence. Multiple heads perform different learned mixtures. A causal mask blocks future positions when predicting the next token, an item such as a word part.", "Transformer blocks also use feed-forward layers, transformations applied to each position, residual connections that add a block's input back to its output, and normalization that controls numerical scale."],
    vocabulary: [word("attention", "attention", "Mixing information using weights computed from how well queries match keys.", "Combining the most relevant notes when answering a question", "Weights 0.75 and 0.25 mix values 2 and 6 into 3.", "A guarantee that a model understands or explains its answer."), word("transformer", "transformer", "A network using repeated attention and per-position transformations with information about position.", "Repeated rounds of consulting notes and revising each note", "Attention exchanges information before each position is processed further.", "Only a single weighted average with no other network operations.")],
    scenario: { title: "Combine two estimates", body: "Two notes estimate a journey at 2 and 6 hours. You give the first note three quarters of the influence and the second one quarter." },
    everydayExample: example("Mix estimates by relevance", "Estimates 2 and 6 hours have weights 0.75 and 0.25.", [["Compute 0.75 × 2 = 1.5 and 0.25 × 6 = 1.5.", "Each weight determines that note's contribution."], ["Add 1.5 + 1.5 = 3 hours.", "Combining the contributions gives the weighted estimate."]], "3 hours", "More weight goes to the first estimate, so the mixture lies closer to 2."),
    mlExample: example("Mix two value representations", "A query matches two keys with equal scores 0 and 0; their scalar values are 2 and 6.", [["Softmax gives exp(0)/(exp(0)+exp(0)) = 1/2 for each key.", "Equal scores give equal normalized weights because exp(0)=1."], ["Compute 0.5 × 2 + 0.5 × 6 = 4.", "Attention multiplies values by those weights and adds the results."]], "Attention output 4", "Scores choose the mixing weights; values supply the information being mixed."),
    task: "Retrieve context by comparing a query with keys, then mixing their value representations.",
    notation: notation("output = α₁v₁ + α₂v₂", "Multiply each value by its attention weight and add the contributions.", [["α₁, α₂", "Weights from query-key scores; here 0.5 each."], ["v₁, v₂", "Values being mixed, here 2 and 6."], ["output", "The resulting representation, here 4."]]),
    questions: [question("attention-story", "What is 0.75 × 2 + 0.25 × 6?", ["8", "3", "4"], 1, "The two contributions are 1.5 each, totaling 3."), question("attention-try", "Weights 0.5 and 0.5 mix values 4 and 8 into what?", ["6", "12", "4"], 0, "Half of 4 plus half of 8 is 2 + 4 = 6."), question("attention-ml", "Which items are multiplied by attention weights?", ["Values", "Target labels", "Learning rates"], 0, "Queries and keys determine weights; the weights mix values.")],
    misconception: { wrong: "Attention weights prove why a model's answer is correct.", correction: "They describe an information mixture. Correctness and explanations require separate evidence." }
  }
};

const everydayQuantities = {
  "tensors-perceptrons": [["Parcels", "2", "Each contributes 3 points."], ["Distance", "1 kilometre", "Each kilometre contributes −1 point."], ["Starting score", "2 points", "Added once to the weighted contributions."]],
  "activations-losses": [["Requests", "−2, 0, 3 units", "The controller's input settings."], ["Minimum heat", "0 units", "Negative requests are clipped to this floor."]],
  "forward-backprop": [["Flour rate", "2 scoops per tray", "Trays determine flour needed."], ["Flour price", "3 coins per scoop", "Scoops determine total cost."]],
  "deep-optimization-regularization": [["Current setting", "3", "The value to adjust."], ["Feedback rate", "4", "Local error increase per setting unit."], ["Step size", "0.1", "Scales the feedback into a cautious adjustment."]],
  "cnn-convolution": [["Shelf counts", "2, 5, 4 items", "The ordered inputs."], ["Comparison weights", "1, −1", "Subtract the right count from the left count."]],
  "sequence-models": [["Starting total", "0 coins", "The memory before any purchase."], ["Purchase prices", "2 then 3 coins", "The next values to add in order."]],
  "attention-transformers": [["Estimates", "2 and 6 hours", "The information to combine."], ["Influence weights", "0.75 and 0.25", "Fractions of the total influence; they sum to 1."]]
};
for (const [id, guide] of Object.entries(DEEP_LEARNING_GUIDES)) {
  guide.everydayExample.quantities = everydayQuantities[id].map(([label, value, meaning]) => ({ label, value, meaning }));
  guide.mlExample.mapping = [{ math: "Model setup", ml: guide.mlExample.prompt }, ...guide.notation.symbols.map(([math, ml]) => ({ math, ml }))];
}
