import { defineFormula } from "./schema.js";

const F = (formula) => defineFormula(formula);

export const formulas = {
  "linear-function": F({
    id: "linear-function",
    category: "Foundations",
    label: "Linear function",
    latex: "f(x)=mx+c",
    readAs: "f of x equals m times x plus c",
    purpose: "Describe a straight-line relationship between an input and an output.",
    symbols: [
      ["f(x)", "the output produced for input x"],
      ["m", "slope: output change for one unit of input"],
      ["x", "the input"],
      ["c", "intercept: output when x is zero"]
    ],
    assumptions: ["The rate of change is constant."],
    beginnerExample: "If a taxi costs 3 per kilometre plus a 5 starting fee, f(4)=3(4)+5=17.",
    derivation: ["Start from the baseline c.", "Add m for every unit of x."],
    signs: ["m>0 rises", "m<0 falls", "m=0 is flat"],
    mistakes: ["Confusing the intercept with the slope."]
  }),
  "summation": F({
    id: "summation",
    category: "Foundations",
    label: "Summation notation",
    latex: "\sum_{i=1}^{n}x_i",
    readAs: "sum x sub i from i equals one to n",
    purpose: "Write repeated addition compactly.",
    symbols: [["\\sum", "add a sequence of terms"], ["i", "the running index"], ["1,n", "start and end positions"], ["x_i", "the value at position i"]],
    assumptions: ["The indexed values x_i are defined for i=1 through n."],
    beginnerExample: "For x=(2,4,6), the sum is 2+4+6=12.",
    derivation: ["Set i=1.", "Add each x_i.", "Stop after i=n."],
    signs: ["The lower and upper limits tell where counting begins and ends."],
    mistakes: ["Treating sigma as multiplication instead of repeated addition."]
  }),
  "logarithm": F({
    id: "logarithm",
    category: "Foundations",
    label: "Logarithm",
    latex: "\log_b(x)=y\iff b^y=x",
    readAs: "log base b of x equals y if and only if b to the y equals x",
    purpose: "Invert exponentiation and turn products into sums.",
    symbols: [["b", "the positive base, not equal to 1"], ["x", "the positive input"], ["y", "the exponent needed to produce x"], ["\\iff", "if and only if"]],
    assumptions: ["b>0", "b\\ne1", "x>0"],
    beginnerExample: "log base 2 of 8 is 3 because 2^3=8.",
    derivation: ["Ask what exponent on b produces x."],
    signs: ["log(x) is negative for 0<x<1 and positive for x>1."],
    mistakes: ["Trying to take the real logarithm of zero or a negative number."]
  }),
  "vector-magnitude": F({
    id: "vector-magnitude",
    category: "Linear Algebra",
    label: "Vector magnitude",
    latex: "\lVert\mathbf v\rVert_2=\sqrt{\sum_{i=1}^{n}v_i^2}",
    readAs: "the L2 length of v is the square root of the sum of its squared coordinates",
    purpose: "Measure vector size independently of direction.",
    symbols: [["\\lVert\\mathbf v\\rVert_2", "Euclidean length of v"], ["v_i", "coordinate i"], ["\\sum", "add across coordinates"]],
    assumptions: ["Coordinates are real numbers."],
    beginnerExample: "For v=(3,4), length=sqrt(9+16)=5.",
    derivation: ["Square each coordinate.", "Add the squares.", "Take the square root."],
    signs: ["Magnitude is always non-negative and is zero only for the zero vector."],
    mistakes: ["Adding coordinates without squaring them."]
  }),
  "unit-vector": F({
    id: "unit-vector",
    category: "Linear Algebra",
    label: "Unit vector / normalization",
    latex: "\hat{\mathbf v}=\frac{\mathbf v}{\lVert\mathbf v\rVert_2}",
    readAs: "v hat equals v divided by its magnitude",
    purpose: "Keep direction while rescaling length to one.",
    symbols: [["\\hat{\\mathbf v}", "normalized vector"], ["\\mathbf v", "original vector"], ["\\lVert\\mathbf v\\rVert_2", "original length"]],
    assumptions: ["v must not be the zero vector."],
    beginnerExample: "(3,4)/5=(0.6,0.8), whose length is 1.",
    derivation: ["Find the magnitude.", "Divide every coordinate by it."],
    signs: ["Normalization preserves the coordinate signs and direction."],
    mistakes: ["Dividing the zero vector by zero."]
  }),
  "distance": F({
    id: "distance",
    category: "Linear Algebra",
    label: "Euclidean distance",
    latex: "d(\mathbf a,\mathbf b)=\lVert\mathbf a-\mathbf b\rVert_2",
    readAs: "distance between a and b equals the length of their difference",
    purpose: "Measure how far two observations are from each other.",
    symbols: [["d", "distance"], ["\\mathbf a-\\mathbf b", "difference vector"], ["\\lVert\\cdot\\rVert_2", "Euclidean length"]],
    assumptions: ["Features use comparable scales or have been scaled."],
    beginnerExample: "Distance from (1,1) to (4,5) is length of (3,4), which is 5.",
    derivation: ["Subtract coordinates.", "Take the magnitude."],
    signs: ["Distance is never negative and is zero only for identical points."],
    mistakes: ["Using raw distance when one feature has a much larger scale."]
  }),
  "dot-product": F({
    id: "dot-product",
    category: "Linear Algebra",
    label: "Dot product",
    latex: "\mathbf a^\top\mathbf b=\sum_{i=1}^{n}a_i b_i=\lVert\mathbf a\rVert\lVert\mathbf b\rVert\cos\theta",
    readAs: "a transpose b equals the sum of matching products, also equal to both lengths times cosine theta",
    purpose: "Measure alignment and compute weighted combinations.",
    symbols: [["\\mathbf a^\\top\\mathbf b", "dot product"], ["a_i b_i", "matching coordinate product"], ["\\theta", "angle between vectors"], ["\\cos\\theta", "directional alignment"]],
    assumptions: ["Vectors have the same number of coordinates."],
    beginnerExample: "(1,2) dot (3,4)=3+8=11.",
    derivation: ["Multiply matching coordinates.", "Add the products."],
    signs: ["Positive means broadly aligned", "zero means perpendicular", "negative means opposed"],
    mistakes: ["Returning a vector instead of one scalar."]
  }),
  "matrix-shape": F({
    id: "matrix-shape",
    category: "Linear Algebra",
    label: "Matrix dimensions",
    latex: "A\in\mathbb R^{m\times n}",
    readAs: "A is a real matrix with m rows and n columns",
    purpose: "State matrix shape formally.",
    symbols: [["A", "matrix"], ["\\mathbb R", "real numbers"], ["m", "rows"], ["n", "columns"]],
    assumptions: ["Entries are real-valued."],
    beginnerExample: "A table with 3 students and 2 features is in R^(3 by 2).",
    derivation: ["Count rows first.", "Count columns second."],
    signs: ["The multiplication sign here separates dimensions; it is not matrix multiplication."],
    mistakes: ["Writing columns before rows."]
  }),
  "matrix-product": F({
    id: "matrix-product",
    category: "Linear Algebra",
    label: "Matrix multiplication",
    latex: "(AB)_{ij}=\sum_{k=1}^{n}A_{ik}B_{kj}",
    readAs: "entry i j of A B is the sum over k of row i of A times column j of B",
    purpose: "Compose transformations and mix features.",
    symbols: [["(AB)_{ij}", "output entry at row i, column j"], ["k", "shared inner dimension"], ["A_{ik}", "row entry from A"], ["B_{kj}", "column entry from B"]],
    assumptions: ["Columns of A equal rows of B."],
    beginnerExample: "A 2x3 matrix times a 3x4 matrix produces a 2x4 matrix.",
    derivation: ["Choose an output row and column.", "Multiply matching entries.", "Add them."],
    signs: ["AB usually does not equal BA."],
    mistakes: ["Multiplying entries position by position."]
  }),
  "transpose": F({
    id: "transpose",
    category: "Linear Algebra",
    label: "Transpose",
    latex: "(A^\top)_{ij}=A_{ji}",
    readAs: "entry i j of A transpose equals entry j i of A",
    purpose: "Swap rows and columns.",
    symbols: [["A^\\top", "transpose"], ["i,j", "row and column indices"]],
    assumptions: ["A may be rectangular; transposition is defined for any matrix."],
    beginnerExample: "[[1,2],[3,4]] transpose becomes [[1,3],[2,4]].",
    derivation: ["Turn each row into a column."],
    signs: ["Transpose changes shape from m by n to n by m."],
    mistakes: ["Changing values instead of only positions."]
  }),
  "determinant": F({
    id: "determinant",
    category: "Linear Algebra",
    label: "2D determinant",
    latex: "\det\begin{pmatrix}a&b\\c&d\end{pmatrix}=ad-bc",
    readAs: "determinant equals a d minus b c",
    purpose: "Measure signed area scaling and detect collapse.",
    symbols: [["\\det(A)", "signed scaling factor"], ["ad-bc", "2 by 2 calculation"]],
    assumptions: ["This shortcut is for a 2 by 2 matrix."],
    beginnerExample: "For [[2,0],[0,3]], determinant=6.",
    derivation: ["Multiply the main diagonal.", "Subtract the other diagonal product."],
    signs: ["Positive preserves orientation", "negative flips orientation", "zero collapses dimension"],
    mistakes: ["Adding bc instead of subtracting it."]
  }),
  "linear-transform": F({
    id: "linear-transform",
    category: "Linear Algebra",
    label: "Linear transformation",
    latex: "T(\mathbf v)=A\mathbf v",
    readAs: "T of v equals matrix A times vector v",
    purpose: "Represent a linear rule with a matrix.",
    symbols: [["T", "transformation"], ["A", "matrix defining the rule"], ["\\mathbf v", "input vector"]],
    assumptions: ["T preserves addition and scalar multiplication.", "T(0)=0."],
    beginnerExample: "A diagonal matrix can stretch horizontal and vertical coordinates by different amounts.",
    derivation: ["Write basis vectors as columns.", "Multiply A by the input coordinates."],
    signs: ["A rule that adds a constant translation is affine, not linear."],
    mistakes: ["Calling every coordinate-moving rule linear."]
  }),
  "eigen-equation": F({
    id: "eigen-equation",
    category: "Linear Algebra",
    label: "Eigen equation",
    latex: "A\mathbf v=\lambda\mathbf v",
    readAs: "A v equals lambda v",
    purpose: "Identify directions that keep their line under a transformation.",
    symbols: [["A", "transformation matrix"], ["\\mathbf v", "eigenvector, nonzero"], ["\\lambda", "eigenvalue or scale factor"]],
    assumptions: ["v is not the zero vector."],
    beginnerExample: "For diag(3,2), the x-axis direction has eigenvalue 3.",
    derivation: ["Apply A to a candidate vector.", "Check whether the output is a scalar multiple."],
    signs: ["Positive lambda keeps direction", "negative lambda flips it", "zero collapses it"],
    mistakes: ["Treating every vector as an eigenvector."]
  }),
  "characteristic-equation": F({
    id: "characteristic-equation",
    category: "Linear Algebra",
    label: "Characteristic equation",
    latex: "\det(A-\lambda I)=0",
    readAs: "determinant of A minus lambda I equals zero",
    purpose: "Find allowable eigenvalues.",
    symbols: [["I", "identity matrix"], ["\\lambda", "candidate eigenvalue"], ["\\det", "determinant"]],
    assumptions: ["A is square."],
    beginnerExample: "For diag(3,2), (3-lambda)(2-lambda)=0, so lambda is 3 or 2.",
    derivation: ["Form A-lambda I.", "Take its determinant.", "Solve for zero."],
    signs: ["The zero determinant means A-lambda I has a nonzero null-space vector."],
    mistakes: ["Subtracting lambda from off-diagonal entries."]
  }),
  "eigendecomposition": F({
    id: "eigendecomposition",
    category: "Linear Algebra",
    label: "Eigendecomposition",
    latex: "A=C\Lambda C^{-1}",
    readAs: "A equals C lambda C inverse",
    purpose: "Change to an eigenvector basis, scale simply, then change back.",
    symbols: [["C", "eigenvectors as columns"], ["\\Lambda", "diagonal matrix of eigenvalues"], ["C^{-1}", "change back to original coordinates"]],
    assumptions: ["A has enough independent eigenvectors to be diagonalizable."],
    beginnerExample: "A diagonal matrix already has C=I and Lambda=A.",
    derivation: ["Find eigenvalues.", "Find matching eigenvectors.", "Build C and Lambda."],
    signs: ["Repeated powers become A^k=C Lambda^k C inverse."],
    mistakes: ["Mismatching the order of eigenvectors and eigenvalues."]
  }),
  "derivative-definition": F({
    id: "derivative-definition",
    category: "Calculus",
    label: "Derivative definition",
    latex: "f'(x)=\lim_{h\to0}\frac{f(x+h)-f(x)}{h}",
    readAs: "f prime x is the limit of the change in f divided by the change h as h approaches zero",
    purpose: "Define instantaneous rate of change.",
    symbols: [["h", "small input change"], ["\\lim_{h\\to0}", "make the change approach zero"], ["f(x+h)-f(x)", "output change"]],
    assumptions: ["The limit exists at x."],
    beginnerExample: "For f(x)=x^2, the limit simplifies to 2x.",
    derivation: ["Compute a nearby secant slope.", "Shrink h toward zero."],
    signs: ["Positive derivative rises", "negative falls", "zero is locally flat"],
    mistakes: ["Setting h=0 before simplifying."]
  }),
  "gradient": F({
    id: "gradient",
    category: "Calculus",
    label: "Gradient",
    latex: "\nabla f(\mathbf x)=\begin{pmatrix}\frac{\partial f}{\partial x_1}\\\vdots\\\frac{\partial f}{\partial x_n}\end{pmatrix}",
    readAs: "gradient of f is the vector of all partial derivatives",
    purpose: "Collect sensitivity to every input direction.",
    symbols: [["\\nabla", "gradient operator"], ["\\partial f/\\partial x_i", "change in f when x_i moves"], ["\\mathbf x", "input vector"]],
    assumptions: ["Required partial derivatives exist."],
    beginnerExample: "For f=x^2+y^2, gradient=(2x,2y).",
    derivation: ["Differentiate once per variable.", "Stack results into a vector."],
    signs: ["The gradient points toward steepest increase; negative gradient points downhill."],
    mistakes: ["Adding partials instead of keeping them as coordinates."]
  }),
  "chain-rule": F({
    id: "chain-rule",
    category: "Calculus",
    label: "Chain rule",
    latex: "\frac{dy}{dx}=\frac{dy}{du}\frac{du}{dx}",
    readAs: "d y by d x equals d y by d u times d u by d x",
    purpose: "Differentiate a composition of functions.",
    symbols: [["u", "intermediate quantity"], ["dy/du", "outer sensitivity"], ["du/dx", "inner sensitivity"]],
    assumptions: ["The component functions are differentiable."],
    beginnerExample: "If y=u^2 and u=3x, dy/dx=2u times 3=18x.",
    derivation: ["Differentiate the outer function.", "Multiply by the inner derivative."],
    signs: ["Several negative local derivatives can change the final sign through multiplication."],
    mistakes: ["Adding local derivatives instead of multiplying them."]
  }),
  "gradient-descent": F({
    id: "gradient-descent",
    category: "Calculus",
    label: "Gradient descent update",
    latex: "\boldsymbol\theta_{t+1}=\boldsymbol\theta_t-\eta\nabla_\theta L(\boldsymbol\theta_t)",
    readAs: "next parameters equal current parameters minus learning rate times the loss gradient",
    purpose: "Update model parameters to reduce loss.",
    symbols: [["\\boldsymbol\\theta", "model parameters"], ["\\eta", "learning rate"], ["L", "loss"], ["\\nabla_\\theta L", "gradient with respect to parameters"]],
    assumptions: ["The loss is differentiable locally."],
    beginnerExample: "If theta=4, gradient=2, eta=0.1, next theta=3.8.",
    derivation: ["Measure uphill direction.", "Scale it by eta.", "Move in the opposite direction."],
    signs: ["Subtract because the gradient points uphill."],
    mistakes: ["Using a learning rate so large that updates overshoot."]
  }),
  "expected-value": F({
    id: "expected-value",
    category: "Probability",
    label: "Expected value",
    latex: "\mathbb E[X]=\sum_x x\,P(X=x)",
    readAs: "expected X is the sum of each outcome times its probability",
    purpose: "Find a probability-weighted long-run average.",
    symbols: [["\\mathbb E[X]", "expected value"], ["x", "possible outcome"], ["P(X=x)", "probability of that outcome"]],
    assumptions: ["Probabilities sum to one."],
    beginnerExample: "Win 10 with probability .4 and lose 8 with .6: expectation=4-4.8=-0.8.",
    derivation: ["Multiply each outcome by its probability.", "Add weighted outcomes."],
    signs: ["Negative player expectation means the game favors the house."],
    mistakes: ["Treating expectation as a guaranteed single outcome."]
  }),
  "variance": F({
    id: "variance",
    category: "Statistics",
    label: "Variance",
    latex: "\operatorname{Var}(X)=\mathbb E[(X-\mu)^2]",
    readAs: "variance of X is the expected squared distance from the mean",
    purpose: "Measure spread around the center.",
    symbols: [["\\mu", "mean of X"], ["X-\\mu", "deviation from the mean"], ["(\\cdot)^2", "square to prevent cancellation"]],
    assumptions: ["The second moment is finite."],
    beginnerExample: "Data close to the mean have small squared deviations and small variance.",
    derivation: ["Subtract the mean.", "Square deviations.", "Average them."],
    signs: ["Variance is never negative; zero means no spread."],
    mistakes: ["Interpreting variance in the original units instead of squared units."]
  }),
  "sample-variance": F({
    id: "sample-variance",
    category: "Statistics",
    label: "Sample variance",
    latex: "s^2=\frac{1}{n-1}\sum_{i=1}^{n}(x_i-\bar x)^2",
    readAs: "sample variance is squared deviations from x bar divided by n minus one",
    purpose: "Estimate population variance from a sample.",
    symbols: [["s^2", "sample variance"], ["\\bar x", "sample mean"], ["n-1", "degrees-of-freedom correction"]],
    assumptions: ["Observations are treated as a sample."],
    beginnerExample: "Use n-1 when three observations are only a sample from a larger population.",
    derivation: ["Find x bar.", "Square deviations.", "Divide by n-1."],
    signs: ["The square keeps variance non-negative."],
    mistakes: ["Using n when the exam asks for sample variance."]
  }),
  "standard-deviation": F({
    id: "standard-deviation",
    category: "Statistics",
    label: "Standard deviation",
    latex: "s=\sqrt{s^2}",
    readAs: "sample standard deviation is the square root of sample variance",
    purpose: "Express typical spread in the original units.",
    symbols: [["s", "sample standard deviation"], ["s^2", "sample variance"], ["\\sqrt{\\cdot}", "returns squared spread to original units"]],
    assumptions: ["Variance has already been computed consistently."],
    beginnerExample: "Variance 9 means standard deviation 3.",
    derivation: ["Compute variance.", "Take its square root."],
    signs: ["Standard deviation is never negative."],
    mistakes: ["Confusing standard deviation with variance."]
  }),
  "z-score": F({
    id: "z-score",
    category: "Statistics",
    label: "Z-score",
    latex: "z=\frac{x-\mu}{\sigma}",
    readAs: "z equals raw value minus mean divided by standard deviation",
    purpose: "Express a value in standard-deviation units.",
    symbols: [["x", "raw value"], ["\\mu", "mean"], ["\\sigma", "population standard deviation"], ["z", "standardized value"]],
    assumptions: ["sigma is positive."],
    beginnerExample: "x=70, mean=50, std=10 gives z=2.",
    derivation: ["Center by subtracting the mean.", "Scale by standard deviation."],
    signs: ["Positive is above mean", "negative is below mean", "magnitude is distance in standard deviations"],
    mistakes: ["Dividing by variance instead of standard deviation."]
  }),
  "covariance": F({
    id: "covariance",
    category: "Statistics",
    label: "Covariance",
    latex: "\operatorname{Cov}(X,Y)=\mathbb E[(X-\mu_X)(Y-\mu_Y)]",
    readAs: "covariance is the expected product of centered X and centered Y",
    purpose: "Measure whether two variables move together.",
    symbols: [["\\mu_X,\\mu_Y", "variable means"], ["X-\\mu_X", "centered X"], ["Y-\\mu_Y", "centered Y"]],
    assumptions: ["Second moments are finite."],
    beginnerExample: "If larger X usually comes with larger Y, covariance tends to be positive.",
    derivation: ["Center both variables.", "Multiply paired deviations.", "Average."],
    signs: ["Positive moves together", "negative moves oppositely", "zero means no linear co-movement"],
    mistakes: ["Assuming zero covariance proves independence."]
  }),
  "correlation": F({
    id: "correlation",
    category: "Statistics",
    label: "Correlation",
    latex: "\rho_{X,Y}=\frac{\operatorname{Cov}(X,Y)}{\sigma_X\sigma_Y}",
    readAs: "correlation equals covariance divided by both standard deviations",
    purpose: "Standardize covariance to a scale from minus one to one.",
    symbols: [["\\rho", "correlation"], ["\\operatorname{Cov}", "covariance"], ["\\sigma_X\\sigma_Y", "scale correction"]],
    assumptions: ["Both standard deviations are positive."],
    beginnerExample: "Correlation near 1 means a strong positive linear relationship.",
    derivation: ["Compute covariance.", "Divide by both spreads."],
    signs: ["+1 perfect positive", "0 no linear relation", "-1 perfect negative"],
    mistakes: ["Treating correlation as proof of causation."]
  }),
  "bayes": F({
    id: "bayes",
    category: "Probability",
    label: "Bayes theorem",
    latex: "P(A\mid B)=\frac{P(B\mid A)P(A)}{P(B)}",
    readAs: "probability of A given B equals likelihood times prior divided by evidence probability",
    purpose: "Update a prior belief after observing evidence.",
    symbols: [["P(A)", "prior"], ["P(B|A)", "likelihood"], ["P(B)", "evidence probability"], ["P(A|B)", "posterior"]],
    assumptions: ["P(B)>0."],
    beginnerExample: "A positive test must be interpreted with disease prevalence, not sensitivity alone.",
    derivation: ["Build likelihood times prior.", "Divide by all ways evidence B occurs."],
    signs: ["The vertical bar means given, and its direction matters."],
    mistakes: ["Confusing P(A|B) with P(B|A)."]
  }),
  "binomial": F({
    id: "binomial",
    category: "Probability",
    label: "Binomial probability",
    latex: "P(X=k)=\binom nk p^k(1-p)^{n-k}",
    readAs: "probability of k successes is n choose k times success and failure probabilities",
    purpose: "Model the number of successes in repeated independent trials.",
    symbols: [["n", "number of trials"], ["k", "success count"], ["p", "constant success probability"], ["\\binom nk", "number of success arrangements"]],
    assumptions: ["Fixed n", "independent trials", "constant p", "two outcomes per trial"],
    beginnerExample: "For 2 fair flips, probability of one head is 2*(.5)^2=.5.",
    derivation: ["Count arrangements.", "Multiply probability of one arrangement."],
    signs: ["1-p is failure probability."],
    mistakes: ["Using binomial when p changes between trials."]
  }),
  "linear-regression": F({
    id: "linear-regression",
    category: "Classical ML",
    label: "Linear regression prediction",
    latex: "\hat y=\mathbf w^\top\mathbf x+b",
    readAs: "predicted y equals weights dot features plus bias",
    purpose: "Predict a continuous target with a weighted sum.",
    symbols: [["\\hat y", "prediction"], ["\\mathbf w", "weights"], ["\\mathbf x", "features"], ["b", "bias or intercept"]],
    assumptions: ["The relationship is approximated linearly in the chosen features."],
    beginnerExample: "House price can be modeled from weighted size, rooms, and age plus a baseline.",
    derivation: ["Multiply each feature by its weight.", "Add results and bias."],
    signs: ["Positive weight raises prediction as its feature grows; negative lowers it."],
    mistakes: ["Reading correlation as a causal weight."]
  }),
  "mse": F({
    id: "mse",
    category: "Classical ML",
    label: "Mean squared error",
    latex: "\operatorname{MSE}=\frac1n\sum_{i=1}^{n}(y_i-\hat y_i)^2",
    readAs: "MSE is the average squared prediction error",
    purpose: "Measure regression error and strongly penalize large misses.",
    symbols: [["y_i", "actual target"], ["\\hat y_i", "prediction"], ["n", "number of examples"]],
    assumptions: ["Targets and predictions use the same units."],
    beginnerExample: "Errors 1 and -3 give MSE=(1+9)/2=5.",
    derivation: ["Find residuals.", "Square them.", "Average."],
    signs: ["MSE is non-negative; zero is perfect fit."],
    mistakes: ["Averaging raw signed residuals, which can cancel."]
  }),
  "ridge": F({
    id: "ridge",
    category: "Classical ML",
    label: "Ridge objective",
    latex: "J(\mathbf w)=\operatorname{MSE}(\mathbf w)+\lambda\lVert\mathbf w\rVert_2^2",
    readAs: "objective equals prediction error plus lambda times squared weight size",
    purpose: "Trade fit quality against overly large weights.",
    symbols: [["J", "objective"], ["\\lambda", "regularization strength"], ["\\lVert\\mathbf w\\rVert_2^2", "squared weight magnitude"]],
    assumptions: ["Features should usually be scaled before comparing weight sizes."],
    beginnerExample: "Larger lambda accepts some error to keep weights smaller.",
    derivation: ["Compute fit error.", "Add weight penalty."],
    signs: ["lambda=0 gives unregularized regression; larger lambda increases shrinkage."],
    mistakes: ["Regularizing the intercept without checking the convention."]
  }),
  "sigmoid": F({
    id: "sigmoid",
    category: "Classical ML",
    label: "Sigmoid",
    latex: "\sigma(z)=\frac{1}{1+e^{-z}}",
    readAs: "sigmoid of z equals one over one plus e to the negative z",
    purpose: "Map any real score into a value between zero and one.",
    symbols: [["z", "raw logit score"], ["e", "Euler's number"], ["\\sigma(z)", "probability-like output"]],
    assumptions: ["For logistic regression, z is usually a linear score."],
    beginnerExample: "z=0 maps to .5.",
    derivation: ["Negate z.", "Exponentiate.", "Add one and invert."],
    signs: ["Positive z gives probability above .5; negative gives below .5."],
    mistakes: ["Calling z itself a probability."]
  }),
  "binary-cross-entropy": F({
    id: "binary-cross-entropy",
    category: "Classical ML",
    label: "Binary cross-entropy",
    latex: "L=-[y\log p+(1-y)\log(1-p)]",
    readAs: "loss is negative y log p plus one minus y log one minus p",
    purpose: "Penalize wrong classification probabilities, especially confident mistakes.",
    symbols: [["y", "true label, zero or one"], ["p", "predicted probability for class one"], ["\\log", "logarithm"]],
    assumptions: ["0<p<1."],
    beginnerExample: "If y=1, loss becomes -log(p), so low p is heavily punished.",
    derivation: ["Use the term selected by y.", "Take negative log probability of the correct class."],
    signs: ["The outer minus makes the loss non-negative."],
    mistakes: ["Using the probability of the wrong class in the log."]
  }),
  "classification-metrics": F({
    id: "classification-metrics",
    category: "Classical ML",
    label: "Precision, recall, and F1",
    latex: "\text{Precision}=\frac{TP}{TP+FP},\quad \text{Recall}=\frac{TP}{TP+FN},\quad F_1=2\frac{PR}{P+R}",
    readAs: "precision measures predicted positives that were correct; recall measures actual positives found",
    purpose: "Evaluate classification beyond accuracy.",
    symbols: [["TP", "true positives"], ["FP", "false positives"], ["FN", "false negatives"], ["F_1", "harmonic mean of precision and recall"]],
    assumptions: ["The positive class is defined clearly."],
    beginnerExample: "Medical screening often prioritizes recall to avoid missing disease.",
    derivation: ["Choose the error type that matters.", "Read the matching denominator."],
    signs: ["Metrics range from zero to one; larger is generally better."],
    mistakes: ["Using accuracy on severely imbalanced data without checking other metrics."]
  }),
  "entropy": F({
    id: "entropy",
    category: "Classical ML",
    label: "Entropy",
    latex: "H(Y)=-\sum_k p_k\log_2p_k",
    readAs: "entropy is negative sum of each class probability times its log",
    purpose: "Measure class uncertainty or impurity.",
    symbols: [["p_k", "probability of class k"], ["H", "entropy"], ["\\log_2", "log base two"]],
    assumptions: ["Class probabilities sum to one."],
    beginnerExample: "A 50-50 binary node has more entropy than a pure 100-0 node.",
    derivation: ["Compute each p log p term.", "Add and negate."],
    signs: ["Entropy is zero for a pure node and larger when classes are mixed."],
    mistakes: ["Forgetting the negative sign."]
  }),
  "gini": F({
    id: "gini",
    category: "Classical ML",
    label: "Gini impurity",
    latex: "G=1-\sum_k p_k^2",
    readAs: "Gini equals one minus the sum of squared class probabilities",
    purpose: "Measure node impurity for decision-tree splitting.",
    symbols: [["G", "Gini impurity"], ["p_k", "class proportion"]],
    assumptions: ["Class proportions sum to one."],
    beginnerExample: "A pure node has Gini 0.",
    derivation: ["Square class proportions.", "Add.", "Subtract from one."],
    signs: ["Lower Gini means purer node."],
    mistakes: ["Choosing a split that increases weighted impurity."]
  }),
  "svm-margin": F({
    id: "svm-margin",
    category: "Classical ML",
    label: "SVM decision function",
    latex: "f(\mathbf x)=\mathbf w^\top\mathbf x+b,\qquad \text{margin}=\frac{2}{\lVert\mathbf w\rVert_2}",
    readAs: "the score is w dot x plus b, and margin width is two over weight length",
    purpose: "Separate classes with the widest robust boundary.",
    symbols: [["\\mathbf w", "boundary normal vector"], ["b", "offset"], ["\\lVert\\mathbf w\\rVert", "controls margin width"]],
    assumptions: ["Features are usually scaled."],
    beginnerExample: "Smaller weight norm means a wider margin when constraints are satisfied.",
    derivation: ["Build a separating hyperplane.", "Maximize distance to nearest points."],
    signs: ["Score sign selects the side of the boundary."],
    mistakes: ["Interpreting a large raw score as a calibrated probability."]
  }),
  "kmeans": F({
    id: "kmeans",
    category: "Classical ML",
    label: "K-means objective",
    latex: "J=\sum_{i=1}^{n}\lVert\mathbf x_i-\boldsymbol\mu_{c_i}\rVert_2^2",
    readAs: "sum squared distance from each point to its assigned cluster center",
    purpose: "Group points around nearby centroids.",
    symbols: [["\\mathbf x_i", "data point"], ["c_i", "assigned cluster"], ["\\boldsymbol\\mu_{c_i}", "assigned centroid"]],
    assumptions: ["Euclidean distance and roughly compact clusters are appropriate."],
    beginnerExample: "Each point joins its nearest center, then centers move to assigned means.",
    derivation: ["Assign nearest centroids.", "Recompute means.", "Repeat."],
    signs: ["The objective is non-negative and should decrease during updates."],
    mistakes: ["Assuming one initialization always finds the global best clustering."]
  }),
  "neuron": F({
    id: "neuron",
    category: "Deep Learning",
    label: "Artificial neuron",
    latex: "\mathbf z=W\mathbf x+\mathbf b,\qquad \mathbf a=\phi(\mathbf z)",
    readAs: "pre-activation z equals weights times inputs plus bias; activation a applies phi",
    purpose: "Mix inputs linearly and then apply a nonlinear transformation.",
    symbols: [["W", "weight matrix"], ["\\mathbf x", "input vector or batch"], ["\\mathbf b", "bias"], ["\\phi", "activation function"]],
    assumptions: ["Matrix dimensions are compatible."],
    beginnerExample: "A dense layer is matrix multiplication plus bias followed by ReLU or another activation.",
    derivation: ["Compute weighted sum.", "Add bias.", "Apply activation."],
    signs: ["Without nonlinear phi, stacked layers collapse to one linear transformation."],
    mistakes: ["Ignoring batch and feature dimensions."]
  }),
  "relu": F({
    id: "relu",
    category: "Deep Learning",
    label: "ReLU",
    latex: "\operatorname{ReLU}(z)=\max(0,z)",
    readAs: "ReLU of z is the larger of zero and z",
    purpose: "Introduce a simple nonlinearity that passes positive values.",
    symbols: [["z", "pre-activation"], ["\\max", "choose the larger value"]],
    assumptions: ["At z=0, implementations choose a derivative convention, commonly zero."],
    beginnerExample: "ReLU(-2)=0 and ReLU(3)=3.",
    derivation: ["If z is negative, output zero.", "Otherwise output z."],
    signs: ["Derivative is zero for negative z and one for positive z, excluding the convention at zero."],
    mistakes: ["Assuming negative inputs remain negative after ReLU."]
  }),
  "softmax": F({
    id: "softmax",
    category: "Deep Learning",
    label: "Softmax",
    latex: "p_i=\frac{e^{z_i}}{\sum_{j=1}^{K}e^{z_j}}",
    readAs: "probability i equals exponentiated score i divided by all exponentiated scores",
    purpose: "Convert multiclass logits into probabilities summing to one.",
    symbols: [["z_i", "logit for class i"], ["K", "number of classes"], ["p_i", "class probability"]],
    assumptions: ["All logits belong to the same example."],
    beginnerExample: "The largest logit gets the largest probability, but all classes still receive a value.",
    derivation: ["Exponentiate logits.", "Add exponentials.", "Divide each by total."],
    signs: ["Probabilities are positive and sum to one."],
    mistakes: ["Applying softmax across the batch dimension."]
  }),
  "multiclass-cross-entropy": F({
    id: "multiclass-cross-entropy",
    category: "Deep Learning",
    label: "Multiclass cross-entropy",
    latex: "L=-\sum_{k=1}^{K}y_k\log p_k",
    readAs: "loss is negative sum of true-label indicators times log probabilities",
    purpose: "Train multiclass classifiers using probabilities.",
    symbols: [["y_k", "one-hot true label"], ["p_k", "predicted class probability"], ["K", "number of classes"]],
    assumptions: ["Probabilities sum to one."],
    beginnerExample: "With one-hot labels, only the true class log probability contributes.",
    derivation: ["Select the true class using y.", "Take negative log of its probability."],
    signs: ["Confident correct predictions approach zero loss; confident wrong predictions have large loss."],
    mistakes: ["Passing probabilities into a framework loss that expects raw logits."]
  }),
  "backprop": F({
    id: "backprop",
    category: "Deep Learning",
    label: "Backpropagation chain",
    latex: "\frac{\partial L}{\partial W^{(l)}}=\frac{\partial L}{\partial \mathbf a^{(l)}}\frac{\partial \mathbf a^{(l)}}{\partial \mathbf z^{(l)}}\frac{\partial \mathbf z^{(l)}}{\partial W^{(l)}}",
    readAs: "loss sensitivity to a layer's weights is the product of local sensitivities along the path",
    purpose: "Assign credit or blame to every weight efficiently.",
    symbols: [["L", "loss"], ["W^{(l)}", "weights at layer l"], ["\\mathbf z", "pre-activation"], ["\\mathbf a", "activation"]],
    assumptions: ["Operations are differentiable or have an agreed subgradient."],
    beginnerExample: "A weight affects z, z affects activation, and activation affects loss; multiply those effects.",
    derivation: ["Start at loss.", "Move backward through operations.", "Multiply local derivatives."],
    signs: ["Gradient sign tells whether increasing a weight raises or lowers loss locally."],
    mistakes: ["Adding derivatives along one chain instead of multiplying them."]
  }),
  "convolution": F({
    id: "convolution",
    category: "Deep Learning",
    label: "2D convolution",
    latex: "Y_{i,j}=\sum_{u}\sum_{v}K_{u,v}X_{i+u,j+v}",
    readAs: "output at i j is the sum of kernel values times the local input patch",
    purpose: "Detect local patterns with shared weights.",
    symbols: [["X", "input image or feature map"], ["K", "kernel"], ["Y", "output feature map"], ["i,j", "output location"]],
    assumptions: ["Padding and stride conventions are specified."],
    beginnerExample: "An edge kernel responds strongly where neighbouring pixels change sharply.",
    derivation: ["Place kernel over a patch.", "Multiply entries.", "Add.", "Slide."],
    signs: ["Positive and negative kernel weights respond to different local contrasts."],
    mistakes: ["Forgetting how padding and stride change output shape."]
  }),
  "rnn": F({
    id: "rnn",
    category: "Deep Learning",
    label: "RNN hidden-state update",
    latex: "\mathbf h_t=\tanh(W_x\mathbf x_t+W_h\mathbf h_{t-1}+\mathbf b)",
    readAs: "current hidden state uses current input and previous hidden state",
    purpose: "Carry information through a sequence.",
    symbols: [["\\mathbf h_t", "current memory state"], ["\\mathbf x_t", "current input"], ["W_h", "recurrent weights"]],
    assumptions: ["The same weights are reused across time."],
    beginnerExample: "A sentence model updates its state one word at a time.",
    derivation: ["Mix current input.", "Mix previous state.", "Add and activate."],
    signs: ["Repeated derivatives can vanish or explode through long sequences."],
    mistakes: ["Treating time steps as independent examples."]
  }),
  "attention": F({
    id: "attention",
    category: "Deep Learning",
    label: "Scaled dot-product attention",
    latex: "\operatorname{Attention}(Q,K,V)=\operatorname{softmax}\!\left(\frac{QK^\top}{\sqrt{d_k}}\right)V",
    readAs: "attention equals softmax of query-key scores scaled by square root d k, then multiplied by values",
    purpose: "Let each token gather information from relevant tokens.",
    symbols: [["Q", "queries: what each token seeks"], ["K", "keys: what each token offers for matching"], ["V", "values: information to combine"], ["d_k", "key dimension"]],
    assumptions: ["Matrix dimensions align and masks are applied when required."],
    beginnerExample: "A pronoun query can place high weight on the earlier noun it refers to.",
    derivation: ["Compare queries with keys.", "Scale scores.", "Softmax into weights.", "Mix values."],
    signs: ["Large positive similarity gets larger attention weight; masking can force forbidden scores away."],
    mistakes: ["Confusing attention weights with the final value vectors."]
  })
};

// Raw template strings preserve LaTeX backslashes that JavaScript string escapes would consume.
const canonicalLatex = {
  "linear-function": String.raw`f(x)=mx+c`,
  summation: String.raw`\sum_{i=1}^{n}x_i`,
  logarithm: String.raw`\log_b(x)=y\iff b^y=x`,
  "vector-magnitude": String.raw`\lVert\mathbf v\rVert_2=\sqrt{\sum_{i=1}^{n}v_i^2}`,
  "unit-vector": String.raw`\hat{\mathbf v}=\frac{\mathbf v}{\lVert\mathbf v\rVert_2}`,
  distance: String.raw`d(\mathbf a,\mathbf b)=\lVert\mathbf a-\mathbf b\rVert_2`,
  "dot-product": String.raw`\mathbf a^\top\mathbf b=\sum_{i=1}^{n}a_i b_i=\lVert\mathbf a\rVert\lVert\mathbf b\rVert\cos\theta`,
  "matrix-shape": String.raw`A\in\mathbb R^{m\times n}`,
  "matrix-product": String.raw`(AB)_{ij}=\sum_{k=1}^{n}A_{ik}B_{kj}`,
  transpose: String.raw`(A^\top)_{ij}=A_{ji}`,
  determinant: String.raw`\det\begin{pmatrix}a&b\\c&d\end{pmatrix}=ad-bc`,
  "linear-transform": String.raw`T(\mathbf v)=A\mathbf v`,
  "eigen-equation": String.raw`A\mathbf v=\lambda\mathbf v`,
  "characteristic-equation": String.raw`\det(A-\lambda I)=0`,
  eigendecomposition: String.raw`A=C\Lambda C^{-1}`,
  "derivative-definition": String.raw`f'(x)=\lim_{h\to0}\frac{f(x+h)-f(x)}{h}`,
  gradient: String.raw`\nabla f(\mathbf x)=\begin{pmatrix}\frac{\partial f}{\partial x_1}\\\vdots\\\frac{\partial f}{\partial x_n}\end{pmatrix}`,
  "chain-rule": String.raw`\frac{dy}{dx}=\frac{dy}{du}\frac{du}{dx}`,
  "gradient-descent": String.raw`\boldsymbol\theta_{t+1}=\boldsymbol\theta_t-\eta\nabla_\theta L(\boldsymbol\theta_t)`,
  "expected-value": String.raw`\mathbb E[X]=\sum_x x\,P(X=x)`,
  variance: String.raw`\operatorname{Var}(X)=\mathbb E[(X-\mu)^2]`,
  "sample-variance": String.raw`s^2=\frac{1}{n-1}\sum_{i=1}^{n}(x_i-\bar x)^2`,
  "standard-deviation": String.raw`s=\sqrt{s^2}`,
  "z-score": String.raw`z=\frac{x-\mu}{\sigma}`,
  covariance: String.raw`\operatorname{Cov}(X,Y)=\mathbb E[(X-\mu_X)(Y-\mu_Y)]`,
  correlation: String.raw`\rho_{X,Y}=\frac{\operatorname{Cov}(X,Y)}{\sigma_X\sigma_Y}`,
  bayes: String.raw`P(A\mid B)=\frac{P(B\mid A)P(A)}{P(B)}`,
  binomial: String.raw`P(X=k)=\binom nk p^k(1-p)^{n-k}`,
  "linear-regression": String.raw`\hat y=\mathbf w^\top\mathbf x+b`,
  mse: String.raw`\operatorname{MSE}=\frac1n\sum_{i=1}^{n}(y_i-\hat y_i)^2`,
  ridge: String.raw`J(\mathbf w)=\operatorname{MSE}(\mathbf w)+\lambda\lVert\mathbf w\rVert_2^2`,
  sigmoid: String.raw`\sigma(z)=\frac{1}{1+e^{-z}}`,
  "binary-cross-entropy": String.raw`L=-[y\log p+(1-y)\log(1-p)]`,
  "classification-metrics": String.raw`\text{Precision}=\frac{TP}{TP+FP},\quad \text{Recall}=\frac{TP}{TP+FN},\quad F_1=2\frac{PR}{P+R}`,
  entropy: String.raw`H(Y)=-\sum_k p_k\log_2p_k`,
  gini: String.raw`G=1-\sum_k p_k^2`,
  "svm-margin": String.raw`f(\mathbf x)=\mathbf w^\top\mathbf x+b,\qquad \text{margin}=\frac{2}{\lVert\mathbf w\rVert_2}`,
  kmeans: String.raw`J=\sum_{i=1}^{n}\lVert\mathbf x_i-\boldsymbol\mu_{c_i}\rVert_2^2`,
  neuron: String.raw`\mathbf z=W\mathbf x+\mathbf b,\qquad \mathbf a=\phi(\mathbf z)`,
  relu: String.raw`\operatorname{ReLU}(z)=\max(0,z)`,
  softmax: String.raw`p_i=\frac{e^{z_i}}{\sum_{j=1}^{K}e^{z_j}}`,
  "multiclass-cross-entropy": String.raw`L=-\sum_{k=1}^{K}y_k\log p_k`,
  backprop: String.raw`\frac{\partial L}{\partial W^{(l)}}=\frac{\partial L}{\partial \mathbf a^{(l)}}\frac{\partial \mathbf a^{(l)}}{\partial \mathbf z^{(l)}}\frac{\partial \mathbf z^{(l)}}{\partial W^{(l)}}`,
  convolution: String.raw`Y_{i,j}=\sum_{u}\sum_{v}K_{u,v}X_{i+u,j+v}`,
  rnn: String.raw`\mathbf h_t=\tanh(W_x\mathbf x_t+W_h\mathbf h_{t-1}+\mathbf b)`,
  attention: String.raw`\operatorname{Attention}(Q,K,V)=\operatorname{softmax}\!\left(\frac{QK^\top}{\sqrt{d_k}}\right)V`
};

for (const [id, latex] of Object.entries(canonicalLatex)) formulas[id].latex = latex;

export const formulaList = Object.values(formulas);
