import { defineProject } from "./schema.js";

export const projects = [
  defineProject({ id: "vector-search-mini", chapterId: "linear-algebra", level: "core", title: "Build a Tiny Similarity Search", summary: "Represent products as vectors, rank them with cosine similarity, and explain one surprising result.", deliverables: ["NumPy similarity function", "Ranked results", "Written interpretation"], skills: ["dot-product", "normalization", "python"] }),
  defineProject({ id: "pca-mini", chapterId: "linear-algebra", level: "advanced", title: "Compress a Dataset with PCA", summary: "Standardize a small dataset, project it to two principal components, and interpret explained variance.", deliverables: ["PCA plot", "Explained-variance table", "Interpretation"], skills: ["eigenvalues", "covariance", "pca"] }),
  defineProject({ id: "optimization-mini", chapterId: "calculus-optimization", level: "core", title: "Visualize Gradient Descent", summary: "Minimize a one-dimensional loss while comparing learning rates.", deliverables: ["Loss curve", "Parameter path", "Learning-rate comparison"], skills: ["gradient", "learning-rate", "python"] }),
  defineProject({ id: "statistics-mini", chapterId: "probability-statistics", level: "core", title: "Audit a Noisy Dataset", summary: "Measure centre, spread, z-scores, covariance, and outliers in a real-looking dataset.", deliverables: ["Summary statistics", "Outlier explanation", "Correlation warning"], skills: ["variance", "z-score", "correlation"] }),
  defineProject({ id: "workflow-mini", chapterId: "classical-ml", level: "basics", title: "Leakage-Proof ML Workflow", summary: "Create a train/validation/test workflow and document where preprocessing is fitted.", deliverables: ["Data split", "Pipeline diagram", "Leakage checklist"], skills: ["data-splits", "leakage", "preprocessing"] }),
  defineProject({ id: "regression-mini", chapterId: "classical-ml", level: "core", title: "Predict and Explain House Prices", summary: "Fit regression, inspect residuals, compare MSE, and explain coefficients in plain English.", deliverables: ["Baseline and model", "Residual plot", "Coefficient interpretation"], skills: ["regression", "mse", "residuals"] }),
  defineProject({ id: "trees-mini", chapterId: "classical-ml", level: "core", title: "Explain a Tree Ensemble", summary: "Compare one decision tree with a random forest and inspect feature importance carefully.", deliverables: ["Model comparison", "Confusion matrix", "Limitations note"], skills: ["trees", "ensembles", "evaluation"] }),
  defineProject({ id: "clustering-mini", chapterId: "classical-ml", level: "core", title: "Discover Customer Segments", summary: "Scale features, select k, fit k-means, and name clusters without overclaiming.", deliverables: ["Elbow analysis", "Cluster plot", "Business interpretation"], skills: ["kmeans", "distance", "scaling"] }),
  defineProject({ id: "classical-capstone", chapterId: "classical-ml", level: "advanced", title: "Classical ML Model Comparison", summary: "Build a reproducible preprocessing and model-selection study with written evaluation.", deliverables: ["Notebook", "Cross-validation table", "Test-set report", "Model card"], skills: ["pipelines", "cross-validation", "model-selection"] }),
  defineProject({ id: "mlp-mini", chapterId: "deep-learning", level: "core", title: "Train a Multilayer Perceptron", summary: "Train a small PyTorch network and connect tensor shapes, loss, and gradients to code.", deliverables: ["Colab notebook", "Learning curves", "Shape trace"], skills: ["tensors", "backprop", "pytorch"] }),
  defineProject({ id: "cnn-mini", chapterId: "deep-learning", level: "core", title: "Classify Images with a CNN", summary: "Train a compact CNN and interpret convolution shapes and common errors.", deliverables: ["Colab notebook", "Confusion matrix", "Error gallery"], skills: ["convolution", "cnn", "evaluation"] }),
  defineProject({ id: "attention-mini", chapterId: "deep-learning", level: "advanced", title: "Implement Scaled Dot-Product Attention", summary: "Implement attention from tensors and explain every matrix shape.", deliverables: ["Attention function", "Shape annotations", "Attention heatmap"], skills: ["attention", "softmax", "matrix-multiplication"] }),
  defineProject({ id: "deep-capstone", chapterId: "deep-learning", level: "advanced", title: "Deep Learning Experiment Report", summary: "Train and debug a PyTorch model with controlled baselines, regularization, and evidence-based conclusions.", deliverables: ["Prepared notebook", "Experiment table", "Failure analysis", "Final report"], skills: ["pytorch", "optimization", "debugging"] })
];

